// Tu dien tieng VIET cho giao dien WEB. Chuoi nguoi dung doc PHẢI co du hai khoa vi + zh
// (xem tai_lieu/SONG-NGU-TRUNG.md) — khong hardcode chuoi trong component.
export const CHUOI_VI = {
  // ================================ chung / ngon ngu
  ngon_ngu: 'Ngôn ngữ',
  ngon_ngu_tieng_viet: 'Tiếng Việt',
  ngon_ngu_tieng_trung: 'Tiếng Trung',

  // ================================ khung: thanh ben + header
  thuong_hieu_phu: 'HR · Chấm công',
  chuyen_goc_nhin: 'Chuyển góc nhìn',
  mo_thanh_dieu_huong: 'Mở thanh điều hướng',
  dong_thanh_dieu_huong: 'Đóng thanh điều hướng',
  quan_tri: 'Quản trị',
  ca_nhan: 'Cá nhân',
  doi_mat_khau: 'Đổi mật khẩu',
  dang_xuat: 'Đăng xuất',

  // ================================ dang nhap
  dang_nhap: 'Đăng nhập',
  dang_nhap_mo_ta: 'Đăng nhập để quản lý chấm công và bảng công.',
  dang_nhap_bang_microsoft: 'Đăng nhập bằng Microsoft',
  hoac: 'hoặc',
  ten_dang_nhap: 'Tên đăng nhập',
  mat_khau: 'Mật khẩu',
  dang_dang_nhap: 'Đang đăng nhập…',
  dang_hoan_tat_dang_nhap: 'Đang hoàn tất đăng nhập…',
  dang_kiem_tra_phien: 'Đang kiểm tra phiên đăng nhập…',
  loi_khong_hoan_tat_sso: 'Không hoàn tất được đăng nhập Microsoft.',

  // ================================ doi mat khau
  doi_mk_hien_tai_do_admin: 'Mật khẩu hiện tại do quản trị đặt. Bạn phải đổi trước khi dùng hệ thống.',
  doi_mk_dang_xuat_moi_thiet_bi: 'Đổi mật khẩu sẽ đăng xuất mọi thiết bị khác.',
  mat_khau_hien_tai: 'Mật khẩu hiện tại',
  mat_khau_moi: 'Mật khẩu mới',
  nhap_lai_mat_khau_moi: 'Nhập lại mật khẩu mới',
  mat_khau_yeu_cau: 'Tối thiểu 8 ký tự, có cả chữ và số.',
  hai_lan_nhap_chua_khop: 'Hai lần nhập chưa khớp.',
  dang_doi: 'Đang đổi…',
  da_doi_mat_khau: 'Đã đổi mật khẩu. Vui lòng đăng nhập lại.',

  // ================================ cho duyet
  cho_phan_quyen: 'Chờ phân quyền',
  cho_duyet_mo_ta: 'Xin chào {ten}. Tài khoản của bạn đã xác thực thành công bằng Microsoft, nhưng chưa được quản trị viên phân quyền nên chưa vào được hệ thống.',
  cho_duyet_luu_y: 'Hãy báo bộ phận nhân sự để được cấp quyền. Sau khi được cấp, bạn chỉ cần đăng nhập lại là dùng được ngay.',
  cho_duyet_chua_co: 'Vẫn chưa được cấp quyền. Thử lại sau khi nhân sự báo đã xong.',
  cho_duyet_dang_kiem: 'Đang kiểm tra…',
  cho_duyet_kiem_lai: 'Tôi đã được cấp quyền — kiểm tra lại',

  // ================================ loi / trang trong
  khong_co_quyen: 'Không có quyền',
  khong_co_quyen_mo_ta: 'Tài khoản của bạn không được xem trang này.',
  khong_co_trang: 'Không có trang này',
  khong_co_trang_mo_ta: 'Đường dẫn {duong_dan} không tồn tại.',
  ve_tong_quan: 'Về tổng quan',

  // ================================ vai tro
  vai_tro_admin: 'Quản trị',
  vai_tro_nhan_su: 'Nhân sự',
  vai_tro_truong_phong: 'Trưởng phòng',
  vai_tro_truong_phong_nhan_su: 'TP nhân sự',
  vai_tro_nhan_vien: 'Nhân viên',
  vai_tro_cho_duyet: 'Chờ phân quyền',
  vai_tro_tbks: 'Trưởng ban kiểm soát',

  // ================================ nhom menu
  nhom_cham_cong: 'Chấm công',
  nhom_luong: 'Lương',
  nhom_nhan_su: 'Nhân sự',
  nhom_cong_viec_to_chuc: 'Công việc & tổ chức',
  nhom_truyen_thong_noi_bo: 'Truyền thông nội bộ',
  nhom_he_thong: 'Hệ thống',
  nhom_nhan_su_luong: 'Nhân sự & lương',
  nhom_tai_khoan_bao_mat: 'Tài khoản & bảo mật',
  nhom_tich_hop_du_lieu: 'Tích hợp & dữ liệu',

  // ================================ khu cai dat
  muc_cai_dat: 'Mục cài đặt',
  cai_dat_mo_ta: 'Các mục cấu hình của hệ thống. Chỉ hiện những mục vai trò của bạn được sửa.',

  // ================================ muc menu + phu
  menu_tong_quan: 'Tổng quan',
  menu_tong_quan_phu: 'Tình hình chấm công hôm nay',
  menu_khu_vuc_cua_toi: 'Khu vực của tôi',
  menu_khu_vuc_cua_toi_phu: 'Chấm công, đơn từ và hồ sơ của bạn',
  menu_cham_cong: 'Chấm công',
  menu_cham_cong_phu: 'Log đồng bộ từ máy ADMS',
  menu_bang_cong: 'Bảng công',
  menu_bang_cong_phu: 'Tổng hợp theo tháng',
  menu_ra_vao: 'Ra/vào',
  menu_ra_vao_phu: 'Cảnh báo ra/vào & xử lý',
  menu_bang_luong: 'Bảng lương',
  menu_bang_luong_phu: 'Tính lương, phiếu từng người',
  menu_phu_cap: 'Phụ cấp',
  menu_phu_cap_phu: 'Danh mục khoản · theo khối · cá nhân',
  menu_ung_luong: 'Ứng lương',
  menu_ung_luong_phu: 'Tạm ứng · duyệt · đã chi',
  menu_khieu_nai_luong: 'Khiếu nại lương',
  menu_khieu_nai_luong_phu: 'Khiếu nại phiếu lương của nhân viên',
  menu_nhan_vien: 'Nhân viên',
  menu_nhan_vien_phu: 'Hồ sơ, PIN máy, tài khoản',
  menu_de_nghi_nhan_su: 'Đề nghị thêm nhân sự',
  menu_de_nghi_nhan_su_phu: 'HR đề nghị, Admin duyệt một bước — hệ thống tự khởi tạo',
  menu_duyet_don: 'Duyệt đơn',
  menu_duyet_don_phu: 'Đơn từ & duyệt',
  menu_quan_ly_phep: 'Quản lý phép',
  menu_quan_ly_phep_phu: 'Tổng hợp ngày phép từng người',
  menu_so_ngoai_le: 'Sổ ngoại lệ',
  menu_so_ngoai_le_phu: 'Ngày bão, sự kiện đặc biệt — miễn đi muộn/về sớm/vắng',
  menu_hop_dong: 'Hợp đồng',
  menu_hop_dong_phu: 'Hạn hợp đồng, tìm trong nội dung',
  menu_ky_luat: 'Kỷ luật & vi phạm',
  menu_ky_luat_phu: 'Nội quy, nhắc nhở, giảm thưởng',
  menu_thoi_viec: 'Thôi việc',
  menu_thoi_viec_phu: 'Quy trình thôi việc: checklist, bàn giao, chốt',
  menu_cong_viec: 'Công việc',
  menu_cong_viec_phu: 'Giao việc, duyệt kết quả, lịch công việc',
  menu_to_chuc: 'Tổ chức & trách nhiệm',
  menu_to_chuc_phu: 'Cơ cấu, vị trí, JD, RACI, bao phủ',
  menu_kpi: 'KPI',
  menu_kpi_phu: 'Chấm điểm từ dữ liệu thật',
  menu_thong_bao: 'Thông báo',
  menu_thong_bao_phu: 'Đăng thông báo / gửi email / popup toàn công ty',
  menu_van_ban: 'Văn bản công ty',
  menu_van_ban_phu: 'Soạn bằng AI, ban hành, tài liệu công ty',
  menu_ho_thu_y_kien: 'Hòm thư ý kiến',
  menu_ho_thu_y_kien_phu: 'Tiếp nhận phản ánh, góp ý & ý kiến dự thảo',
  menu_cong_bo_phat_hanh: 'Công bố phát hành',
  menu_cong_bo_phat_hanh_phu: 'AI tổng hợp tính năng mới, gửi thông báo + popup',
  menu_cai_dat: 'Cài đặt',
  menu_cai_dat_phu: 'Chấm công, lương, tài khoản, tích hợp',
  menu_thiet_bi: 'Thiết bị',
  menu_thiet_bi_phu: 'Máy chấm công ZKTeco',
  menu_ca_lam: 'Ca làm việc',
  menu_ca_lam_phu: 'Giờ vào/ra, dung sai, ngưỡng OT',
  menu_dia_diem: 'Địa điểm',
  menu_dia_diem_phu: 'Đối chiếu GPS khi đi công tác',
  menu_ngay_le: 'Ngày lễ',
  menu_ngay_le_phu: 'Tết Nguyên đán phải tự thêm mỗi năm',
  menu_lam_bu: 'Ngày làm bù',
  menu_lam_bu_phu: 'Ngày được nghỉ, kiếm công bằng buổi làm bù',
  menu_tham_so_luong: 'Tham số lương',
  menu_tham_so_luong_phu: 'BHXH, thuế TNCN, giảm trừ gia cảnh',
  menu_tai_khoan: 'Tài khoản',
  menu_tai_khoan_phu: 'Người dùng và vai trò',
  menu_khoa_api: 'Khóa API',
  menu_khoa_api_phu: 'Cho hệ thống ngoài gọi vào',
  menu_nhat_ky: 'Nhật ký thao tác',
  menu_nhat_ky_phu: 'Ai sửa gì, khi nào',
  menu_dong_bo_erp: 'Đồng bộ ERP',
  menu_dong_bo_erp_phu: 'Kéo người dùng từ ERP cũ',
  menu_kho_tep: 'Kho tệp hồ sơ',
  menu_kho_tep_phu: 'Tệp đính kèm và đường dẫn đã lưu',
  menu_ma_dinh_danh: 'Mã định danh',
  menu_ma_dinh_danh_phu: 'Tra cứu theo mã, đối soát các nguồn',

  // ================================ khu vuc cua toi: vo + man trang chu
  cn_loi_man_hinh: 'Màn này đang gặp lỗi hiển thị',
  cn_loi_man_hinh_mo_ta: 'Các màn khác vẫn dùng bình thường — bấm sang tab khác rồi quay lại, hoặc tải lại trang. Nếu vẫn lỗi, gửi giúp nhân sự dòng chi tiết dưới đây.',
  cn_ban: 'bạn',
  cn_tab_trang_chu: 'Trang chủ',
  cn_tab_don_tu: 'Đơn từ',
  cn_tab_luong: 'Lương',
  cn_tab_phep: 'Phép',
  cn_tab_khieu_nai: 'Khiếu nại',
  cn_tab_ca_nhan: 'Cá nhân',
  cn_ten_man_bang_cong: 'Bảng công của tôi',
  cn_ten_man_bang_cong_phu: 'Số liệu chấm công theo tháng',
  cn_ten_man_don_tu: 'Nghỉ phép & đơn từ',
  cn_ten_man_don_tu_phu: 'Xin nghỉ, giải trình, theo dõi trạng thái duyệt',
  cn_ten_man_luong: 'Phiếu lương',
  cn_ten_man_luong_phu: 'Cơ sở tính lương của kỳ',
  cn_ten_man_phep: 'Quản lý phép',
  cn_ten_man_phep_phu: 'Quỹ phép năm & lịch sử nghỉ của bạn',
  cn_ten_man_khieu_nai: 'Khiếu nại lương',
  cn_ten_man_khieu_nai_phu: 'Lập & theo dõi khiếu nại phiếu lương, trao đổi với Nhân sự',
  cn_ten_man_viec: 'Công việc của tôi',
  cn_ten_man_viec_phu: 'Việc được giao, hạn hoàn thành và các bước cần làm',
  cn_ten_man_y_kien: 'Hòm thư ý kiến',
  cn_ten_man_y_kien_phu: 'Gửi góp ý, phản ánh, thắc mắc và theo dõi phản hồi của Nhân sự',
  cn_ten_man_ca_nhan: 'Cá nhân',
  cn_ten_man_ca_nhan_phu: 'Hồ sơ, tài liệu, hợp đồng, BHXH, cài đặt',
  cn_xin_chao: 'Xin chào, {ten}',
  cn_thong_bao_phu_de: 'Thông báo từ BGĐ & nhân sự',
  cn_van_ban_phu_de: 'Nội quy, biểu mẫu, chính sách',
  cn_ve_goc_nhin_quan_tri: 'Về góc nhìn Quản trị',
  cn_chua_gan_ca_lam_viec: 'Chưa gán ca làm việc',
  cn_ve_man_truoc: 'Về màn trước',
  cn_ve_trang_chu: 'Về Trang chủ',
  cn_cac_man_khu_vuc: 'Các màn khu vực của tôi',
  cn_thu_tuc_thoi_viec_mo: 'Thủ tục thôi việc đang mở',
  cn_con_muc_bat_buoc: 'Còn {n} mục bắt buộc chưa xong — hoàn tất để Admin chốt.',
  cn_moi_muc_xong: 'Mọi mục đã xong — chờ Admin duyệt cuối ở Cổng 2.',
  cn_mo_huong_dan: 'Mở hướng dẫn',
  cn_cong_thang: 'Công tháng',
  cn_ngay_da_co_du_lieu: '{n} ngày đã có dữ liệu',
  cn_di_muon: 'Đi muộn',
  cn_lan_x: '{n} lần',
  cn_tong_x: 'tổng {n}',
  cn_ot_ghi_nhan: 'OT ghi nhận',
  cn_chua_qua_duyet: 'chưa qua duyệt',
  cn_phep_con: 'Phép còn',
  cn_ngay_x: '{n} ngày',
  cn_ngay_cho_duyet: '{n} ngày chờ duyệt',
  cn_khong_co_don_cho_duyet: 'không có đơn chờ duyệt',
  cn_gio_vao: 'GIỜ VÀO',
  cn_gio_ra: 'GIỜ RA',
  cn_chua_co_du_lieu_cham_cong: 'chưa có dữ liệu chấm công hôm nay',
  cn_hom_nay_vang: 'hôm nay vắng',
  cn_hom_nay_nghi_phep: 'hôm nay nghỉ phép',
  cn_di_muon_x: 'đi muộn {n}',
  cn_dung_gio_vao_ca: 'đúng giờ vào ca',
  cn_chua_quet_vao: 'chưa quẹt vào',
  cn_da_quet_ra: 'đã quẹt ra',
  cn_chua_quet_ra: 'chưa quẹt ra',
  cn_con_x_den_gio: 'còn {n} đến {g}',
  cn_qua_gio_ra: 'Quá giờ ra · {n}',
  cn_dang_lam: 'Đang làm · {n}',
  cn_da_ket_thuc_ca: 'Đã kết thúc ca hôm nay',
  cn_vao_ca: 'vào ca',
  cn_het_ca: 'hết ca',
  cn_quet_tai_may: 'Quẹt tại máy chấm công',
  cn_lam_moi: 'Làm mới',
  cn_xin_nghi_phep: 'Xin nghỉ phép',
  cn_con_ngay_phep: 'Còn {n} ngày phép',
  cn_giai_trinh_quen_quet: 'Giải trình quên quẹt',
  cn_bu_gio_thieu: 'Bù giờ vào / ra bị thiếu',
  cn_don_cua_toi: 'Đơn của tôi',
  cn_don_dang_cho_duyet: '{n} đơn đang chờ duyệt',
  cn_dang_ky_ot: 'Đăng ký OT',
  cn_lam_them_gio_duyet_2_cap: 'Làm thêm giờ — duyệt 2 cấp',
  cn_don_khac: 'Đơn khác',
  cn_don_khac_phu: 'Làm thêm, đổi ca, công tác, đi muộn, về sớm, Remote',
  cn_nghi_phep_phu: 'Phép năm, không lương, ốm…',
  cn_gio_lam_7_ngay: 'Giờ làm 7 ngày gần nhất',
  cn_vach_mo_8_gio: 'Vạch mờ = 8 giờ chuẩn của ca hành chính.',
  cn_cac_lan_quet: 'Các lần quẹt hôm nay',
  cn_chua_co_lan_quet: 'Chưa có lần quẹt nào',
  cn_du_lieu_hien_ngay: 'Dữ liệu hiện ngay sau khi bạn quẹt.',
  cn_tuan_nay: 'Tuần này',
  cn_chuyen_can_thang: 'Chuyên cần tháng này',
  cn_so_ngay_du_cong: 'Số ngày đủ công, không đi muộn — tính đến hôm nay.',
  cn_chua_co_du_lieu_thang: 'Chưa có dữ liệu tháng này.',
  cn_bang_cong_xuat_hien: 'Bảng công sẽ xuất hiện khi máy chấm công đẩy log về.',
  cn_can_chu_y_sap_toi: 'Cần chú ý & sắp tới',
  cn_ngay_thieu_gio_quet: '{n} ngày thiếu giờ quẹt',
  cn_bo_sung_giai_trinh: 'Bổ sung bằng giải trình quên quẹt',
  cn_giai_trinh: 'Giải trình',
  cn_theo_doi_don_tu: 'Theo dõi trạng thái ở màn Đơn từ',
  cn_xem_don: 'Xem đơn',
  cn_don_cho_ban_duyet: '{n} đơn đang chờ bạn duyệt',
  cn_ban_la_nguoi_duyet: 'Bạn là người duyệt của phòng mình',
  cn_di_duyet: 'Đi duyệt',
  cn_khong_co_viec_can_chu_y: 'Không có việc cần chú ý',
  cn_cong_va_don_on: 'Công hôm nay và đơn từ đều ổn',

  // ================================ khu vuc cua toi: nhan trang thai ngay cong
  cn_tt_nghi_phep: 'Nghỉ phép',
  cn_tt_nghi_khong_luong: 'Nghỉ không lương',
  cn_tt_lam_bu: 'Làm bù',
  cn_tt_ngoai_le: 'Ngoại lệ',
  cn_tt_cong_tac: 'Công tác',
  cn_tt_lam_remote: 'Làm Remote',
  cn_tt_vang: 'Vắng',
  cn_tt_ngay_le: 'Ngày lễ',
  cn_tt_nghi_tuan: 'Nghỉ tuần',
  cn_tt_thieu_gio_quet: 'Thiếu giờ quẹt ({n})',
  cn_tt_di_muon: 'Đi muộn {n}',
  cn_tt_du_cong: 'Đủ công',
  cn_tt_co_mat: 'Có mặt',
  cn_thieu_gio_vao: 'thiếu giờ vào',
  cn_thieu_gio_ra: 'thiếu giờ ra',

  // ================================ khu vuc cua toi: man bang cong
  cn_thang_truoc: 'Tháng trước',
  cn_thang_sau: 'Tháng sau',
  cn_thang_x: 'tháng {n}',
  cn_tong_cong: 'TỔNG CÔNG',
  pc_canh_bao_ngay_hl:
    'Ngày hiệu lực không nằm trong kỳ lương đang mở nào — khoản sẽ không vào phiếu lương khi bấm "Tính lương".',
  nv_cong_chuan_rieng: 'Công chuẩn riêng',
  nv_cong_chuan_rieng_phu:
    'Số công chuẩn cố định mỗi tháng của riêng người này. Để trống = theo khối, rồi tham số chung, rồi đếm theo lịch. Dùng cho ngoại lệ đã duyệt (ví dụ 30 công/tháng).',
  cn_gio_lam: 'GIỜ LÀM',
  cn_tang_ca: 'TĂNG CA',
  cn_chi_tiet_tung_ngay: 'Chi tiết từng ngày',
  cn_muon_thieu_gio: 'muộn/thiếu giờ',
  cn_cong: 'công',
  cn_muon_phut: 'muộn {n}′',
  cn_ve_som_phut: 'về sớm {n}′',
  cn_thieu_gio_vao_mui_ten: 'thiếu giờ vào → {r}',
  cn_dang_ky_lam_them_ot: 'Đăng ký làm thêm (OT) →',
  cn_thay_sai_lech: 'Thấy sai lệch? Gửi giải trình quên quẹt →',
  cn_lich_thang: 'Lịch tháng',
  cn_ngay_chua_co_du_lieu: 'Ngày chưa có dữ liệu',
  cn_chua_den: 'Chưa đến',

  // ================================ khu vuc cua toi: don tu
  cn_quy_phep_nam_x: 'Quỹ phép năm {n}',
  cn_con: 'còn',
  cn_da_dung_x_ngay: 'Đã dùng {n} ngày',
  cn_chua_tru_x_ngay: 'chưa trừ {n} ngày đang chờ duyệt',
  cn_tat_ca: 'Tất cả',
  cn_dang_cho: 'Đang chờ ({n})',
  cn_da_duyet: 'Đã duyệt',
  cn_tu_choi: 'Từ chối',
  cn_khong_co_don_o_loc: 'Không có đơn nào ở bộ lọc này',
  cn_chon_tat_ca_xem: 'Chọn “Tất cả” để xem toàn bộ đơn đã gửi.',
  cn_da_gui: 'Đã gửi',
  cn_nguoi_duyet: 'Người duyệt',
  cn_hoan_tat: 'Hoàn tất',
  cn_huy_don_nay: 'Hủy đơn này?',
  cn_huy_don_mo_ta: 'Đơn sẽ được đánh dấu đã hủy và người duyệt không cần xử lý nữa.',
  cn_huy_don: 'Hủy đơn',
  cn_da_huy_don: 'Đã hủy đơn.',
  cn_ly_do_x: 'Lý do: {n}',
  cn_duyet_cap_1: 'Đã duyệt cấp 1 (trưởng phòng) — đang chờ TBKS/Admin duyệt cấp 2. Duyệt xong, bạn nộp kết quả OT bằng ảnh.',
  cn_nop_ket_qua_ot: 'Nộp kết quả OT',
  cn_don_giai_trinh_khong_huy: 'Đơn giải trình không tự hủy được — nhờ nhân sự xử lý.',
  cn_loai_nghi: 'LOẠI NGHỈ',
  cn_thoi_gian_nghi: 'THỜI GIAN NGHỈ',
  cn_ca_ngay: 'Cả ngày',
  cn_nua_ngay: '½ ngày',
  cn_tu_ngay: 'Từ ngày',
  cn_den_ngay: 'Đến ngày',
  cn_nghi_nua_ngay_x: 'Nghỉ ½ ngày {n}',
  cn_ngay_nghi_khoang: '{n} ngày nghỉ, {tu} → {den}',
  cn_con_lai_ngay_phep: 'còn lại {n} ngày phép',
  cn_ly_do: 'Lý do',
  cn_viec_gia_dinh: 'Việc gia đình…',
  cn_huy: 'Hủy',
  cn_gui_don: 'Gửi đơn',
  cn_da_gui_don: 'Đã gửi đơn. Người duyệt sẽ nhận thông báo ngay.',
  cn_ngay_thieu_gio_he_thong: 'NGÀY THIẾU GIỜ — HỆ THỐNG PHÁT HIỆN',
  cn_ngay: 'Ngày',
  cn_gio_vao_de_xuat: 'Giờ vào đề xuất',
  cn_gio_ra_de_xuat: 'Giờ ra đề xuất',
  cn_ly_do_bat_buoc: 'Lý do (bắt buộc)',
  cn_may_khong_nhan_khuon_mat: 'Máy không nhận khuôn mặt, đi họp ngoài…',
  cn_chi_dien_moc_thieu: 'Chỉ điền mốc giờ bị thiếu. Nhân sự duyệt xong, bảng công sẽ tự tính lại.',
  cn_gui_giai_trinh: 'Gửi giải trình',
  cn_da_gui_giai_trinh: 'Đã gửi giải trình. Nhân sự duyệt xong, bảng công sẽ tự tính lại.',
  cn_lam_don: 'Làm đơn',
  cn_loai_don: 'LOẠI ĐƠN',
  cn_luu_y_doi_ca: 'Đổi ca cần nhân sự chọn ca mới trên hồ sơ. Đơn ở đây là đề nghị, không tự đổi ca của bạn.',
  cn_luu_y_thoi_viec: 'Đơn thôi việc phải báo trước theo hợp đồng: 30 ngày với hợp đồng xác định thời hạn, 45 ngày với hợp đồng không xác định thời hạn.',
  cn_luu_y_lam_them: 'Tổng làm thêm không vượt 40 giờ/tháng. Hệ thống sẽ cảnh báo khi đơn vượt trần.',
  cn_luu_y_ve_som: 'Đơn được duyệt thì hôm đó bạn không bị mất nửa ngày công dù về sớm quá 30 phút.',
  cn_luu_y_lam_remote: 'Ngày làm Remote được duyệt sẽ tính đủ công, không cần quẹt máy.',
  cn_tu_gio: 'Từ giờ',
  cn_den_gio: 'Đến giờ',
  cn_gio_du_kien_ra_ve: 'Giờ dự kiến ra về',
  cn_noi_den: 'Nơi đến',
  cn_noi_dung_cong_tac: 'Nội dung công tác',
  cn_dang_ky_lam_them_tieu_de: 'Đăng ký làm thêm giờ (OT)',
  cn_ngay_lam_them: 'NGÀY LÀM THÊM',
  cn_tai_lieu_kem: 'Tài liệu đính kèm (không bắt buộc — 1 tệp PDF/JPG/PNG)',
  cn_da_chon_tep: 'Đã chọn: {n}',
  cn_hop_ot_2_cap: 'Đơn OT duyệt qua hai cấp: trưởng phòng rồi TBKS/Admin. Duyệt xong, bạn nộp kết quả bằng ảnh thì OT mới được tính công. Tổng làm thêm không vượt 40 giờ/tháng.',
  cn_ket_qua_ot: 'Kết quả OT · {n}',
  cn_ket_qua_ot_huong_dan: 'Đơn đã duyệt xong — gửi 1 đến 5 ảnh chụp kết quả làm việc để TBKS duyệt và OT được tính công.',
  cn_kq_da_nop: 'Kết quả đã nộp — đang chờ TBKS duyệt. Nộp lại sẽ thay thế bản cũ.',
  cn_kq_da_duyet: 'Kết quả đã được duyệt — OT đã được tính công.',
  cn_kq_tu_choi: 'Kết quả bị từ chối{n}. Bạn có thể nộp lại.',
  cn_anh_ket_qua: 'Ảnh kết quả (1–5 ảnh JPG/PNG)',
  cn_da_chon_x_anh: 'Đã chọn {n} ảnh: {ten}',
  cn_ghi_chu_khong_bat_buoc: 'Ghi chú (không bắt buộc)',
  cn_dong: 'Đóng',
  cn_dang_gui: 'Đang gửi…',
  cn_nop_ket_qua: 'Nộp kết quả',
  cn_da_nop_kq_ot: 'Đã nộp kết quả OT. TBKS/Admin sẽ duyệt và OT được tính vào bảng công.',
  cn_loai_lam_them: 'Làm thêm giờ',
  cn_loai_doi_ca: 'Đổi ca',
  cn_loai_cong_tac: 'Công tác',
  cn_loai_thoi_viec: 'Thôi việc',
  cn_loai_di_muon: 'Đi muộn',
  cn_loai_ve_som: 'Về sớm',
  cn_loai_lam_remote: 'Làm Remote',
  cn_td_nghi_phep_nam: 'Nghỉ phép năm',
  cn_td_nghi_khong_luong: 'Nghỉ không lương',
  cn_td_nghi_om: 'Nghỉ ốm',
  cn_td_nghi_thai_san: 'Nghỉ thai sản',
  cn_td_nghi_ket_hon: 'Nghỉ kết hôn',
  cn_td_nghi_hieu: 'Nghỉ việc hiếu',
  cn_loai_phep_nam: 'Phép năm',
  cn_loai_khong_luong: 'Không lương',
  cn_loai_om: 'Nghỉ ốm',
  cn_loai_thai_san: 'Thai sản',
  cn_loai_ket_hon: 'Kết hôn',
  cn_loai_hieu: 'Nghỉ hiếu',
  cn_ra_ve_x: 'ra về {n}',
  cn_de_xuat_khoang: 'đề xuất {v} – {r}',
  cn_nua_ngay_dot: ' · ½ ngày',

  // ================================ khu vuc cua toi: man luong
  cn_ky_truoc: 'Kỳ trước',
  cn_ky_sau: 'Kỳ sau',
  cn_ky_thang_x: 'Kỳ tháng {n}',
  cn_ky_chua_co_phieu: 'Kỳ này chưa có phiếu lương.',
  cn_duoi_day_du_lieu_cham_cong: 'Dưới đây là dữ liệu chấm công sẽ được dùng làm căn cứ — kiểm tra sớm để phát hiện sai lệch trước khi chốt.',
  cn_cong_thuc_te: 'Công thực tế',
  cn_da_tru_gio_nghi_trua: 'đã trừ giờ nghỉ trưa',
  cn_chua_duyet_tra_them: 'chưa duyệt trả thêm',
  cn_khong_phep: 'không phép',
  cn_cong_thuc_te_chuan: 'Công thực tế / công chuẩn',
  cn_chi_tiet_ky_thang: 'Chi tiết kỳ tháng {n}',
  cn_ngay_co_mat: 'Ngày có mặt',
  cn_ve_som: 'Về sớm',
  cn_chot_roi: 'Kỳ công này đã chốt — số liệu dưới đây là căn cứ cuối cùng.',
  cn_chua_chot: 'Kỳ này chưa chốt. Một lần quẹt về muộn hoặc một đơn được duyệt vẫn có thể làm số liệu thay đổi.',
  cn_chot_roi_phieu: 'Kỳ công này đã chốt — số liệu trên phiếu là căn cứ cuối cùng.',
  cn_chua_chot_phieu: 'Kỳ này chưa chốt — số liệu trên phiếu vẫn có thể thay đổi.',

  // ================================ khu vuc cua toi: man ca nhan (ho so)
  cn_thong_tin_chung: 'Thông tin chung',
  cn_tai_lieu: 'Tài liệu',
  cn_hop_dong: 'Hợp đồng',
  cn_luong: 'Lương',
  cn_nguoi_phu_thuoc: 'Người phụ thuộc',
  cn_bhxh_bhyt: 'BHXH – BHYT',
  cn_cong_viec: 'Công việc',
  cn_thiet_bi: 'Thiết bị',
  cn_cai_dat: 'Cài đặt',
  cn_tk_chua_noi_ho_so: 'Tài khoản chưa nối với hồ sơ nhân viên',
  cn_nho_nhan_su_gan: 'Nhờ nhân sự gán tài khoản này vào hồ sơ của bạn thì thông tin cá nhân mới hiện ra ở đây.',
  cn_vao_lam_x: 'vào làm {n}',
  cn_tham_nien_x: 'thâm niên {n}',
  cn_nam_thang_x: '{n} năm {m} tháng',
  cn_x_thang: '{n} tháng',
  cn_x_nam: '{n} năm',
  cn_chua_co_hop_dong_hieu_luc: 'Chưa có hợp đồng hiệu lực',
  cn_ho_so_tai_lieu: 'Hồ sơ tài liệu',
  cn_du_tai_lieu_bat_buoc: 'Đủ tài liệu bắt buộc',
  cn_con_thieu_tai_lieu: 'còn thiếu {n} tài liệu bắt buộc',
  cn_xem_chi_tiet: 'Xem chi tiết',
  cn_pin_may: 'PIN máy',
  cn_so_tren_may: 'số trên máy chấm công',
  cn_ngay_vao: 'Ngày vào',
  cn_chinh_thuc_x: 'chính thức {n}',
  cn_chua_co_ngay_chinh_thuc: 'chưa có ngày chính thức',
  cn_hop_dong_hien_tai: 'Hợp đồng hiện tại',
  cn_den_x: 'đến {n}',
  cn_kxd_thoi_han: 'không xác định thời hạn',
  cn_luong_hien_tai: 'Lương hiện tại',
  cn_chua_co_qd_luong: 'chưa có quyết định lương',
  cn_phu_cap_x_dong: 'phụ cấp {n} ₫ · {m}',
  cn_thong_tin_ca_nhan: 'Thông tin cá nhân',
  cn_sai_thong_tin: 'Sai thông tin? Gửi yêu cầu sửa cho nhân sự — bạn không tự sửa được hồ sơ gốc.',
  cn_ho_va_ten: 'Họ và tên',
  cn_ngay_sinh: 'Ngày sinh',
  cn_gioi_tinh: 'Giới tính',
  cn_nam: 'Nam',
  cn_nu: 'Nữ',
  cn_dien_thoai: 'Điện thoại',
  cn_email_cong_ty: 'Email công ty',
  cn_noi_o_hien_tai: 'Nơi ở hiện tại',
  cn_ma_so_thue: 'Mã số thuế',
  cn_tk_va_cham_cong: 'Tài khoản & chấm công',
  cn_ma_nhan_vien: 'Mã nhân viên',
  cn_pin_tren_may: 'PIN trên máy chấm công',
  cn_chua_cap: 'Chưa cấp',
  cn_cham_cong_dt: 'Chấm công bằng điện thoại',
  cn_duoc_phep: 'Được phép',
  cn_khong_quet_tai_may: 'Không — quẹt tại máy',
  cn_mui_gio_tinh_cong: 'Múi giờ tính công',
  cn_trang_thai: 'Trạng thái',
  cn_dang_lam_viec: 'Đang làm việc',
  cn_da_nghi_viec: 'Đã nghỉ việc',
  cn_tien_do_ho_so: 'Tiến độ hồ sơ bắt buộc',
  cn_chi_tinh_du_khi: 'Chỉ tính là đủ khi tài liệu ở mức “Đã lên phần mềm”. Tài liệu chỉ phát sinh khi nghỉ việc được tạm miễn.',
  cn_tt_da_len_phan_mem: 'Đã lên phần mềm',
  cn_tt_da_so_hoa: 'Đã số hóa',
  cn_tt_da_co_du_lieu: 'Đã có dữ liệu',
  cn_tt_thieu: 'Thiếu',
  cn_tai_lieu_do_nhan_su: 'Tài liệu do nhân sự đăng và cập nhật. Thiếu tài liệu nào, nhờ nhân sự bổ sung.',
  cn_hop_dong_hd_null: 'Chưa có hợp đồng hiệu lực trong hệ thống. Bản giấy đã ký vẫn có giá trị — nhắc nhân sự đăng lên để hồ sơ đủ.',
  cn_loai_hop_dong: 'Loại hợp đồng',
  cn_thoi_han: 'Thời hạn',
  cn_ngay_ky: 'Ngày ký',
  cn_so_hop_dong: 'Số hợp đồng',
  cn_chuc_danh: 'Chức danh',
  cn_noi_lam_viec: 'Nơi làm việc',
  cn_hieu_luc: 'Hiệu lực',
  cn_tu_x: 'từ {n}',
  cn_luong_co_ban: 'Lương cơ bản',
  cn_luong_phu_cap: 'Lương & phụ cấp',
  cn_so_lieu_do_nhan_su: 'Số liệu do nhân sự chốt. Phiếu lương từng kỳ xem ở màn Lương.',
  cn_muc_luong: 'Mức lương',
  cn_hinh_thuc_tra: 'Hình thức trả',
  cn_so_quyet_dinh: 'Số quyết định',
  cn_hieu_luc_tu: 'Hiệu lực từ',
  cn_qh_con: 'Con',
  cn_qh_vo_chong: 'Vợ / chồng',
  cn_qh_cha: 'Cha',
  cn_qh_me: 'Mẹ',
  cn_qh_anh_chi_em: 'Anh chị em',
  cn_qh_khac: 'Khác',
  cn_hd_thu_viec: 'Thử việc',
  cn_hd_xac_dinh: 'Xác định thời hạn',
  cn_hd_kxd: 'Không xác định thời hạn',
  cn_hd_thoi_vu: 'Thời vụ',
  cn_hd_ctv: 'Cộng tác viên',
  cn_hd_hoc_viec: 'Học việc',
  cn_ht_thang: 'Theo tháng',
  cn_ht_ngay: 'Theo ngày',
  cn_ht_gio: 'Theo giờ',
  cn_ht_san_pham: 'Sản phẩm',
  cn_ht_khoan: 'Khoán',
  cn_bh_moi: 'Mới',
  cn_bh_da_nop: 'Đã nộp',
  cn_bh_cq_duyet: 'Cơ quan duyệt',
  cn_bh_tu_choi: 'Từ chối',
  cn_bh_hoan_thanh: 'Hoàn thành',
  cn_lbh_bao_tang: 'Báo tăng',
  cn_lbh_bao_giam: 'Báo giảm',
  cn_lbh_dieu_chinh: 'Điều chỉnh',
  cn_lbh_chot_so: 'Chốt sổ',
  cn_lbh_cap_the: 'Cấp thẻ BHYT',
  cn_lbh_om_dau: 'Ốm đau',
  cn_lbh_thai_san: 'Thai sản',
  cn_lbh_duong_suc: 'Dưỡng sức',
  cn_lbh_tnld: 'Tai nạn lao động',

  // ================================ khu vuc cua toi: man phep
  cn_quy_phep_nam: 'Quỹ phép năm',
  cn_chi_nghi_phep_tru: 'Chỉ nghỉ PHÉP NĂM đã duyệt mới trừ vào quỹ. Nghỉ ốm / không lương không trừ phép.',
  cn_tong_quy_phep: 'Tổng quỹ phép',
  cn_da_dung: 'Đã dùng',
  cn_con_lai: 'Còn lại',
  cn_dang_cho_duyet: 'Đang chờ duyệt',
  cn_chi_tiet_cac_lan_nghi: 'Chi tiết các lần nghỉ (năm {n})',
  cn_chua_co_lan_nghi: 'Chưa có lần nghỉ nào trong năm.',
  cn_nua_ngay_suffix: '(nửa ngày)',
  cn_nam_truoc: 'Năm trước',
  cn_nam_sau: 'Năm sau',
  cn_phep_nam_x: 'Phép năm {n}',
  cn_tt_cho_duyet: 'Chờ duyệt',
  cn_tt_da_duyet: 'Đã duyệt',
  cn_tt_tu_choi: 'Từ chối',
  cn_tt_da_huy: 'Đã hủy',

  // ================================ khu vuc cua toi: phu thuoc + bhxh + cong viec + thiet bi + cai dat
  cn_chua_khai_pt: 'Chưa khai người phụ thuộc',
  cn_pt_mo_ta: 'Người phụ thuộc dùng để giảm trừ thuế TNCN. Gửi giấy tờ chứng minh cho nhân sự để đăng ký.',
  cn_giam_tru: 'Giảm trừ',
  cn_den_x_khoang: ' đến {n}',
  cn_con_hieu_luc: ' · còn hiệu lực',
  cn_chua_co_khoang: 'chưa có khoảng áp dụng',
  cn_da_dang_ky: 'Đã đăng ký',
  cn_chua_dang_ky: 'Chưa đăng ký',
  cn_so_so_bhxh: 'Số sổ BHXH',
  cn_chua_co: 'Chưa có',
  cn_ma_the_bhyt: 'Mã thẻ BHYT',
  cn_co_quan_bhxh: 'Cơ quan BHXH',
  cn_noi_kcb_bd: 'Nơi khám chữa bệnh ban đầu',
  cn_cac_su_kien_gan_day: 'Các sự kiện gần đây',
  cn_muc_dong_x: 'mức đóng {n} ₫',
  cn_ho_so_x: ' · hồ sơ {n}',
  cn_vi_tri_hien_tai: 'Vị trí hiện tại',
  cn_phong_ban: 'Phòng ban',
  cn_quan_ly_truc_tiep: 'Quản lý trực tiếp',
  cn_ca_lam_viec: 'Ca làm việc',
  cn_chua_gan_ca: 'Chưa gán ca',
  cn_lich_su_cong_viec: 'Lịch sử công việc',
  cn_tiep_nhan: 'Tiếp nhận',
  cn_ket_thuc_thu_viec: 'Kết thúc thử việc',
  cn_chua_xac_nhan_tt: 'Chưa xác nhận kết thúc thử việc',
  cn_chua_co_thiet_bi: 'Chưa có thiết bị cấp phát',
  cn_thiet_bi_mo_ta: 'Laptop, thẻ từ… do nhân sự ghi vào hồ sơ khi bàn giao.',
  cn_loai: 'Loại',
  cn_hang: 'Hãng',
  cn_so_seri: 'Số seri',
  cn_ngay_nhan: 'Ngày nhận',
  cn_tinh_trang: 'Tình trạng',
  cn_dang_dung: 'Đang dùng',
  cn_dx_khoi_ung_dung: 'Đăng xuất khỏi ứng dụng?',
  cn_dx_mo_ta: 'Bạn sẽ phải đăng nhập lại bằng tên đăng nhập và mật khẩu. Dữ liệu chấm công không bị ảnh hưởng.',
  cn_may_chu_noi_bo: 'Máy chủ nội bộ · {n}',
  cn_mui_gio_tinh_cong_utc: 'Múi giờ tính công UTC+{n}',
  cn_mk_nhap_lai_khong_khop: 'Mật khẩu nhập lại không khớp.',
  cn_da_doi_mk_chuyen: 'Đã đổi mật khẩu. Đang chuyển về trang đăng nhập…',

  // ================================ thong bao ca nhan
  tb_thuong: 'Thường',
  tb_quan_trong: 'Quan trọng',
  tb_khan: 'Khẩn',
  tb_can_giai_trinh: 'Cần giải trình',
  tb_xem_ai_da_doc: 'Xem ai đã đọc',
  tb_tai_van_ban: 'Tải văn bản (DOCX)',
  tb_tai_x: 'Tải: {n}',
  tb_da_gui_email: '✉ Đã gửi email',
  tb_dang_gui: 'Đang gửi…',
  tb_gui_email: 'Gửi email',
  tb_chua_gui_duoc: 'Chưa gửi được: {n}',
  tb_da_giai_trinh: 'Đã giải trình{ma}{luc}: {nd}',
  tb_giai_trinh_cua_ban: 'Giải trình của bạn (bắt buộc)',
  tb_nhap_giai_trinh: 'Nhập giải trình / cam kết…',
  tb_gui_giai_trinh: 'Gửi giải trình',
  tb_da_doc_x: '✓ Đã đọc {n}',
  tb_da_doc_hieu: 'Đã đọc & hiểu',
  tb_dang_luu: 'Đang lưu…',
  tb_dang_thong_bao: '+ Đăng thông báo',
  tb_dang_thong_bao_moi: 'Đăng thông báo mới',
  tb_tieu_de: 'Tiêu đề',
  tb_noi_dung: 'Nội dung',
  tb_tep_kem_tuy_chon: 'Tệp đính kèm (tùy chọn — PDF/JPG/PNG/DOCX/XLSX, gửi kèm email)',
  tb_meo_trinh_bay: 'Mẹo trình bày email: {a} → tiêu đề có viền xanh · {b} đầu dòng → gạch đầu dòng · {c} → in đậm.',
  tb_muc_do: 'Mức độ',
  tb_bat_buoc_giai_trinh: 'Bắt buộc giải trình',
  tb_hien_popup: 'Hiện popup khi mở app (bắt buộc đọc)',
  tb_gui_email_toan_cty: 'Gửi email tới toàn công ty',
  tb_dang_dang: 'Đang đăng…',
  tb_dang: 'Đăng',
  tb_xem_truoc_email: 'Xem trước email',
  tb_xem_truoc_email_cn: 'Xem trước email (bấm "Xem trước email" lại để cập nhật)',
  tb_da_doc_tua: 'Đã đọc — {n}',
  tb_chua_ai_xac_nhan: 'Chưa ai xác nhận đọc',
  tb_nhan_vien: 'Nhân viên',
  tb_phong: 'Phòng',
  tb_doc_luc: 'Đọc lúc',
  tb_giai_trinh_cot: 'Giải trình',
  tb_loc_thong_bao: 'Lọc thông báo',
  tb_toan_cong_ty_x: 'Toàn công ty ({n})',
  tb_tat_ca_x: 'Tất cả ({n})',
  tb_chua_co_thong_bao: 'Chưa có thông báo',
  tb_khi_dang_thi_hien: 'Khi công ty đăng thông báo, nó sẽ hiện ở đây.',
  tb_da_gui_gt_ok: 'Đã gửi giải trình.',
  tb_da_xac_nhan_doc: 'Đã xác nhận đã đọc.',
  tb_da_gui_email_ok: 'Đã gửi email.',
  tb_da_dang_thong_bao: 'Đã đăng thông báo.',

  // ================================ phieu luong cua toi
  pl_chua_co_phieu: 'Chưa có phiếu lương',
  pl_phieu_hien_sau: 'Phiếu lương hiện sau khi kế toán chốt và duyệt kỳ lương của tháng.',
  pl_phieu_luong: 'Phiếu lương',
  pl_nhan_vien_x: 'Nhân viên: {n}',
  pl_ky_thang_xy: 'Kỳ tháng {m}/{n}',
  pl_chuyen_ky: 'Chuyển kỳ lương',
  pl_ky_truoc: 'Kỳ trước',
  pl_ky_sau: 'Kỳ sau',
  pl_tai_pdf: 'Tải PDF',
  pl_xuat_file: 'Xuất file',
  pl_thuc_nhan: 'Thực nhận',
  pl_da_lam_tron_tu: 'đã làm tròn từ {n} đ',
  pl_du_cong: 'Đủ công',
  pl_mien_phat: 'Miễn phạt',
  pl_tong_thu_nhap: 'Tổng thu nhập',
  pl_khoan_x: '{n} khoản',
  pl_tong_khau_tru: 'Tổng khấu trừ',
  pl_ti_trong: 'Tỉ trọng',
  pl_khau_tru_chiem: 'Khấu trừ trên tổng thu nhập chiếm {n}%',
  pl_thu_nhap: 'Thu nhập',
  pl_luong_cb_theo_cong: 'Lương cơ bản (theo công)',
  pl_cong_xy: '{n}/{m} công',
  pl_phu_cap_theo_cong: 'Phụ cấp (theo công)',
  pl_d_thang_xy: '{n}đ/tháng × {m}/{k}',
  pl_luong_theo_cong: 'Lương theo công',
  pl_lam_them_gio: 'Làm thêm giờ (OT)',
  pl_ngay_thuong: 'Ngày thường',
  pl_he_so_x: 'hệ số {n}',
  pl_chu_nhat: 'Chủ nhật',
  pl_ngay_le: 'Ngày lễ',
  pl_mien_thue: ' (miễn thuế)',
  pl_thuong: 'Thưởng',
  pl_phu_cap_khac: 'Phụ cấp khác',
  pl_khau_tru: 'Khấu trừ',
  pl_tien_luong_dong: 'Tiền lương đóng: {n} đ',
  pl_sau_giam_tru: 'sau giảm trừ',
  pl_tru_khac: 'Trừ khác',
  pl_da_mien_phat_ky: 'Đã miễn phạt đi muộn/về sớm kỳ này (không trừ).',
  pl_cac_lan_dm_vs: 'Các lần đi muộn về sớm',
  pl_can_cu_tinh_luong: 'Căn cứ tính lương',
  pl_cong_chuan: 'Công chuẩn',
  pl_luong_ngay_cong: 'Lương/ngày công',
  pl_muc_dong_bh: 'Mức đóng BH',
  pl_giam_tru_gia_canh: 'Giảm trừ gia cảnh',
  pl_thu_nhap_tinh_thue: 'Thu nhập tính thuế',
  pl_phep_nam: 'Phép năm',
  pl_con_ngay_xy: 'Còn {n} / {m} ngày',
  pl_da_dung_x_ngay: 'Đã dùng {n} ngày',
  pl_x_dang_cho_duyet: '{n} đang chờ duyệt',
  pl_co_so_cham_cong: 'Cơ sở tính lương (chấm công)',
  pl_gio_cong: 'Giờ công',
  pl_da_duyet_tu_tren: 'đã duyệt từ trên',
  pl_tong_x_ngay: 'Tổng: {n} ngày có dữ liệu',
  pl_chua_co_du_lieu_ky: 'Chưa có dữ liệu chấm công của kỳ này.',
  pl_chi_tiet_ky: 'Chi tiết kỳ tháng {m}/{n}',
  pl_quen_cham_cong: 'Quên chấm công',
  pl_sai_so_lieu: 'Sai số liệu? Gửi khiếu nại. Nhấn sửa để soát trong 3 ngày.',
  pl_khieu_nai: 'Khiếu nại',
  pl_chi_hien_khi_duyet: 'Phiếu lương chỉ hiện khi kỳ đã được duyệt/trả. Nếu thấy sai, bấm Khiếu nại phiếu lương này để gửi Phòng Nhân sự, hoặc gửi giải trình ở mục Đơn của tôi — mỗi khoản đều ghi rõ để đối chiếu.',
  pl_khieu_nai_phieu_x: 'Khiếu nại phiếu lương {n}',
  pl_mo_ta_khoan: 'Mô tả rõ khoản bạn cho là chưa đúng (công, thưởng, phụ cấp, khấu trừ…) để Phòng Nhân sự đối chiếu và phản hồi.',
  pl_noi_dung_kn: 'Nội dung khiếu nại',
  pl_anh_kem: 'Ảnh đính kèm (có thể chọn nhiều ảnh — tùy chọn)',
  pl_da_chon_x_anh: 'Đã chọn {n} ảnh: {ten}',
  pl_gui_khieu_nai: 'Gửi khiếu nại',
  pl_da_gui_kn: 'Đã gửi khiếu nại.',
  pl_tra_loi_bo_sung: 'Trả lời / bổ sung thông tin cho Phòng Nhân sự…',
  pl_gui_tra_loi: 'Gửi trả lời',
  pl_da_gui_tra_loi: 'Đã gửi trả lời.',
  pl_them_anh_minh_chung: 'Thêm ảnh minh chứng (có thể chọn nhiều):',
  pl_da_them_x_anh: 'Đã thêm {n} ảnh.',
  pl_khieu_nai_cua_ban: 'Khiếu nại phiếu lương của bạn',
  pl_ticket_da_dong: 'Ticket đã đóng ({n}).',
  pl_lap_khieu_nai: 'Lập khiếu nại phiếu lương',
  pl_chua_co_phieu_kn: 'Chưa có phiếu lương đã duyệt nào để khiếu nại.',
  pl_chon_ky: 'Chọn kỳ lương',
  pl_lap_kn_ky_nay: 'Lập khiếu nại kỳ này',
  pl_chua_co_kn: 'Chưa có khiếu nại nào',
  pl_kn_mo_ta: 'Khi bạn gửi khiếu nại phiếu lương, nó hiện ở đây kèm trạng thái xử lý và trao đổi với Nhân sự.',
  pl_tt_moi: 'Mới',
  pl_tt_dang_xem: 'Đang xem xét',
  pl_tt_chap_nhan: 'Đã chấp nhận',
  pl_tt_tu_choi: 'Đã từ chối',
  pl_thang_xy: 'Tháng {m}/{n}',
  pl_da_tra: 'Đã trả',
  pl_lan: 'lần',
  pl_ngay_unit: 'ngày',
  pl_ky_x: 'Kỳ {n}',
  pl_csv_muc: 'Mục',
  pl_csv_loai: 'Loại',
  pl_csv_so_luong: 'Số lượng',
  pl_csv_don_gia: 'Đơn giá',
  pl_csv_thanh_tien: 'Thành tiền',
  pl_csv_ghi_chu: 'Ghi chú',
  pl_csv_thuc_nhan: 'Thực nhận',

  // ================================ hom thu y kien cua toi
  yk_y_kien_du_thao: 'Ý kiến dự thảo',
  yk_gop_y: 'Góp ý',
  yk_phan_anh: 'Phản ánh',
  yk_yeu_cau: 'Yêu cầu',
  yk_thac_mac: 'Thắc mắc',
  yk_cho_xu_ly: 'Chờ xử lý',
  yk_da_tiep_nhan: 'Đã tiếp nhận',
  yk_da_hoan_tat: 'Đã hoàn tất',
  yk_gui_y_kien_moi: 'Gửi ý kiến mới',
  yk_ma_vb_du_thao: 'Mã văn bản dự thảo (tùy chọn)',
  yk_khong_gan_vb: 'Không gắn văn bản (góp ý chung)',
  yk_chon_ma_vb: 'Chọn mã văn bản để góp ý dự thảo',
  yk_du_thao: 'Dự thảo',
  yk_han_x: ' (hạn {n})',
  yk_loai_y_kien: 'Loại ý kiến',
  yk_chon_loai: 'Chọn loại',
  yk_vi_du_tieu_de: 'Ví dụ: Đề xuất thêm quạt cho dây chuyền may',
  yk_trinh_bay_ro: 'Trình bày rõ ý kiến, băn khoăn hoặc yêu cầu của bạn…',
  yk_gui_y_kien: 'Gửi ý kiến',
  yk_chua_gui_y_kien: 'Bạn chưa gửi ý kiến nào',
  yk_moi_gop_y: 'Mọi góp ý, phản ánh, yêu cầu đều được Phòng Nhân sự tiếp nhận và phản hồi.',
  yk_mo_lai_du_thao: 'mở lại dự thảo',
  yk_thu_gon: 'Thu gọn',
  yk_xem_trao_doi: 'Xem trao đổi ({n})',
  yk_trao_doi_them: 'Trao đổi thêm với Phòng Nhân sự…',
  yk_da_gui_ok: 'Đã gửi. Phòng Nhân sự sẽ tiếp nhận và phản hồi qua đây và qua email của bạn.',
  yk_da_gui_dt: 'Đã gửi ý kiến cho dự thảo. Phòng Nhân sự sẽ tiếp nhận và phản hồi.',

  // ================================ hom thu y kien — tab gop y du thao
  ht_gop_y_du_thao: 'Góp ý dự thảo',
  ht_han_gop_y: 'Hạn góp ý',
  ht_khong_co_du_thao: 'Không có dự thảo nào đang mở để góp ý.',
  ht_gop_y_ngay: 'Góp ý',
  ht_gop_y_mo_ta: 'Danh sách các dự thảo văn bản đang mở lấy ý kiến trong phạm vi của bạn. Mở một dự thảo để đọc nội dung, xem tệp đính kèm và gửi ý kiến của mình.',

  // ================================ cong viec cua toi
  vt_khong_con_viec: 'Không còn việc nào đang chờ bạn.',
  vt_con_viec_x: 'Bạn đang còn {n} việc chưa xong.',
  vt_danh_sach: 'Danh sách',
  vt_lich_gantt: 'Lịch (gantt)',
  vt_chua_co_cong_viec: 'Chưa có công việc nào',
  vt_khi_giao_viec: 'Khi được giao việc, bạn sẽ thấy ở đây kèm hạn và các bước cần làm.',
  vt_qua_han: 'Quá hạn ({n})',
  vt_den_han: 'Đến hạn ({n})',
  vt_dang_lam: 'Đang làm ({n})',
  vt_moi_giao: 'Mới giao ({n})',
  vt_cho_duyet: 'Chờ duyệt ({n})',
  vt_da_xong: 'Đã xong ({n})',
  vt_khong_co: 'Không có',
  vt_han_x: 'hạn {n} {g}',
  vt_buoc_xy: '{x}/{y} bước',

  // ================================ dashboard ca nhan
  dcn_tong_quan_rieng: 'Đây là tổng quan của riêng bạn trong tháng {n}.',
  dcn_ban_co_tb: 'Bạn có {n} thông báo cần giải trình.',
  dcn_mo_ngay: 'Mở ngay →',
  dcn_cong_thang_nay: 'Công tháng này',
  dcn_co_mat_x_ngay: 'Có mặt {n} ngày',
  dcn_phep_con_lai: 'Phép còn lại',
  dcn_da_dung_xy: 'Đã dùng {x}/{y}',
  dcn_thong_bao_moi: 'Thông báo mới',
  dcn_chua_doc_bam: 'Chưa đọc — bấm để xem',
  dcn_da_doc_het: 'Đã đọc hết',
  dcn_don_cho_duyet: 'Đơn chờ duyệt',
  dcn_nghi_phep_giai_trinh: 'Nghỉ phép, giải trình',
  dcn_nghi_le_sap_toi: 'Nghỉ lễ sắp tới',
  dcn_chua_co_ngay_le: 'Sắp tới chưa có ngày lễ nào trong lịch.',
  dcn_loi_tat: 'Lối tắt',
  dcn_xin_nghi_giai_trinh: 'Xin nghỉ / giải trình',
  dcn_thong_bao_cty: 'Thông báo công ty',
  dcn_tai_lieu_cty: 'Tài liệu công ty',
  dcn_ho_so_cua_toi: 'Hồ sơ của tôi',
  dcn_khong_tai_duoc: 'Không tải được tổng quan.',

  // ================================ tro ly ca nhan
  tl_mo_tro_ly: 'Mở trợ lý',
  tl_tro_ly_nhan_su: 'Trợ lý nhân sự',
  tl_xoa_lich_su: 'Xóa lịch sử',
  tl_xoa_toan_bo: 'Xóa toàn bộ lịch sử hội thoại của bạn',
  tl_xoa: 'Xóa',
  tl_dang_tra_loi: 'Đang trả lời',
  tl_cho_xac_nhan: 'Chờ xác nhận',
  tl_xin_loi: 'Xin lỗi, mình chưa trả lời được lúc này.',
  tl_yeu_cau_khong_hop_le: 'Yêu cầu này không hợp lệ, mình không gửi được.',
  tl_luu_y: 'Lưu ý:',
  tl_da_gui_thanh_cong: 'Đã gửi thành công: {n}. Bạn xem trạng thái ở tab "Đơn của tôi".{them}',
  tl_khong_ket_noi: 'Không kết nối được máy chủ.',
  tl_may_chu_ban: 'Máy chủ đang bận hoặc vừa khởi động lại — bạn bấm lại sau ít phút nhé.',
  tl_chua_gui_duoc: 'Chưa gửi được: {n}',
  tl_da_bo_qua: 'Đã bỏ qua — không có gì được gửi đi.',
  tl_cau_hoi: 'Câu hỏi',
  tl_hoi_phong: 'Hỏi phép, công, OT, đổi ca, nội quy…',
  tl_gui: 'Gửi',

  // ================================ tro ly thoi viec
  tv_tro_ly_thoi_viec: 'Trợ lý thủ tục thôi việc',
  tv_thu_tuc_thoi_viec: 'Thủ tục thôi việc',
  tv_con_x_muc: 'Còn {n} mục bắt buộc chưa xong.',
  tv_muc_ke_tiep: 'Mục kế tiếp: {n}.',
  tv_ngay_lv_cuoi: 'Ngày làm việc cuối: {n}',
  tv_xac_nhan_x: 'Xác nhận: {n}',
  tv_mo_huong_dan_tv: 'Mở hướng dẫn thủ tục',

  // ================================ popup thong bao
  pp_khan: 'KHẨN',
  pp_giai_trinh_bat_buoc: 'Giải trình (bắt buộc)',
  pp_nhap_giai_trinh: 'Nhập giải trình của bạn…',
  pp_yeu_cau_nhap: 'Thông báo này yêu cầu bạn nhập giải trình (tối thiểu 5 ký tự).',
  pp_gui_gt_xac_nhan: 'Gửi giải trình & xác nhận',
  pp_con_x_tb: 'Còn {n} thông báo nữa',

  // ================================ chuong bao
  cb_chua_doc_x: '({n} chưa đọc)',
  cb_danh_dau_da_doc: 'Đánh dấu đã đọc',
  cb_tat_ca: 'Tất cả',
  cb_chua_xem: 'Chưa xem',
  cb_cho_duyet: 'Chờ duyệt',
  cb_khong_con_chua_xem: 'Không còn thông báo chưa xem.',
  cb_khong_co_cho_duyet: 'Không có thông báo nào đang chờ duyệt.',
  cb_chua_co_thong_bao: 'Chưa có thông báo nào.',
  cb_da_xem: 'Đã xem',

  // ================================ van ban cong ty (phan ca nhan)
  vb_van_ban_ban_hanh: 'Văn bản ban hành',
  vb_van_ban_cong_ty_phu: 'Thông báo, văn bản ban hành có số hiệu và tài liệu công ty — một nơi duy nhất.',
  vb_cac_muc_vb: 'Các mục văn bản công ty',
  vb_chua_co_van_ban: 'Chưa có văn bản',
  vb_nhan_su_se_dang: 'Nhân sự sẽ đăng thông báo, nội quy, biểu mẫu tại đây.',
  vb_tai: 'Tải',
  vb_chua_co_vb_ban_hanh: 'Chưa có văn bản ban hành',
  vb_van_ban_cho_ban: 'Văn bản có số ký hiệu phát hành cho bạn sẽ hiện ở đây.',
  vb_so_ky_hieu: 'Số ký hiệu',
  vb_loai: 'Loại',
  vb_trich_yeu: 'Trích yếu',
  vb_phat_hanh: 'Phát hành',
  vb_tai_docx: 'Tải DOCX',
  vb_dm_quyet_dinh: 'Quyết định',
  vb_dm_cong_van: 'Công văn',
  vb_dm_noi_quy: 'Nội quy',
  vb_dm_bieu_mau: 'Biểu mẫu',
  vb_dm_chinh_sach: 'Chính sách',
  vb_dm_huong_dan: 'Hướng dẫn',
  vb_dm_khac: 'Khác',

  // ================================ nhan dung chung (thanh_phan.tsx)
  thp_cho_duyet_2: 'Chờ TBKS/Admin',
  thp_tu_dong: 'Tự động',
  thp_nguon_may: 'Máy chấm công',
  thp_nguon_dien_thoai: 'Điện thoại',
  thp_nguon_thu_cong: 'Nhập tay',
  tep_keo_tha: 'Kéo thả tệp vào đây hoặc bấm để chọn',
  tep_bo_chon: 'Bỏ chọn',
  tep_chon_csv: 'Chọn tệp CSV',

  // ================================ soan van ban thu cong (van_ban.tsx)
  vb_soan_van_ban: '+ Soạn văn bản',
  vb_soan_va_ban_hanh: 'Soạn & ban hành văn bản',
  vb_so_hieu_tu_cap: 'Số hiệu được cấp tự động khi ban hành (VB-…).',
  vb_loai_hinh_thuc: 'Loại / hình thức',
  vb_loai_hinh_thuc_phu: 'Loại / hình thức văn bản',
  vb_nguoi_ban_hanh: 'Người ban hành',
  vb_nguoi_ban_hanh_phu: 'vd Giám đốc, Phòng HCNS',
  vb_noi_dung_van_ban: 'Nội dung văn bản',
  vb_noi_dung_phu: 'Soạn nội dung thông báo / văn bản tại đây…',
  vb_tep_kem: 'Tệp đính kèm (tùy chọn — PDF, DOCX, XLSX, ảnh)',
  vb_pham_vi: 'Phạm vi',
  vb_pham_vi_nhan: 'Phạm vi nhận văn bản',
  vb_toan_cong_ty: 'Toàn công ty',
  vb_phong_ban: 'Phòng ban',
  vb_ca_nhan: 'Cá nhân',
  vb_chon_phong_ban: 'Chọn phòng ban',
  vb_phong_ban_nhan: 'Phòng ban nhận văn bản',
  vb_chon_nhan_vien: 'Chọn nhân viên',
  vb_nhan_vien_nhan: 'Nhân viên nhận văn bản',
  vb_chon: '— Chọn —',
  vb_gui_he_thong: 'Gửi thông báo hệ thống (hiện ở chuông báo, theo dõi đã đọc)',
  vb_gui_email: 'Gửi email (qua Microsoft 365 — bỏ qua nếu chưa cấu hình)',
  vb_dang_ban_hanh: 'Đang ban hành…',
  vb_ban_hanh: 'Ban hành',
  vb_da_ban_hanh: 'Đã ban hành văn bản.',

  // ================================ van ban AI (thong_bao_ai.tsx)
  vai_dang_soan: 'Đang soạn',
  vai_cho_duyet: 'Chờ duyệt',
  vai_cho_ky: 'Chờ ký',
  vai_loi: 'Lỗi',
  vai_dang_lay_y_kien: 'Đang lấy ý kiến',
  vai_da_phat_hanh: 'Đã phát hành',
  vai_da_huy: 'Đã hủy',
  vai_loai_thong_bao: 'Thông báo',
  vai_loai_quyet_dinh: 'Quyết định',
  vai_loai_cong_van: 'Công văn',
  vai_md_nhac_nho: 'Nhắc nhở',
  vai_md_yeu_cau: 'Yêu cầu',
  vai_md_pho_bien: 'Phổ biến',
  vai_md_moi_hop: 'Mời họp',
  vai_md_phoi_hop: 'Đề nghị phối hợp',
  vai_loi_chon_nhan_vien: 'Phạm vi cá nhân phải chọn nhân viên nhận.',
  vai_loi_chon_phong_ban: 'Phạm vi phòng ban phải chọn phòng ban.',
  vai_loi_ngay_nghi_viec: 'Quyết định nghỉ việc phải có ngày nghỉ việc.',
  vai_da_tao_ban_nhap: 'Đã tạo bản nháp. Hệ thống đang soạn văn bản…',
  vai_da_tao_va_tai_tep: 'Đã tạo bản nháp và tải tệp đính kèm lên.',
  vai_soan_bang_ai: '+ Soạn văn bản bằng AI',
  vai_soan_van_ban_moi: 'Soạn văn bản mới',
  vai_thong_tin_co_ban: 'Thông tin cơ bản',
  vai_loai_van_ban: 'Loại văn bản',
  vai_pham_vi_nhan: 'Phạm vi nhận',
  vai_quan_he: 'Quan hệ',
  vai_noi_bo: 'Nội bộ',
  vai_doi_ngoai: 'Đối ngoại',
  vai_quan_he_van_ban: 'Quan hệ văn bản',
  vai_muc_dich: 'Mục đích',
  vai_muc_dich_van_ban: 'Mục đích văn bản',
  vai_nguoi_nhan: 'Người nhận',
  vai_phong_ban_nhan: 'Phòng ban nhận',
  vai_chon_phong_ban_x: '— Chọn phòng ban —',
  vai_nhan_vien_nhan: 'Nhân viên nhận',
  vai_chon_nhan_vien_x: '— Chọn nhân viên —',
  vai_qd_nghi_viec: 'Quyết định nghỉ việc',
  vai_la_qd_nghi_viec: 'Đây là quyết định nghỉ việc',
  vai_ngay_nghi_viec: 'Ngày nghỉ việc (tài khoản tự khóa sau ngày này)',
  vai_che_do_soan: 'Chế độ soạn',
  vai_che_do: 'Chế độ',
  vai_ai_soan: 'AI soạn (nhập ý vắn tắt)',
  vai_tu_soan: 'Tự soạn (không dùng AI)',
  vai_hieu_luc_den: 'Hiệu lực đến (bỏ trống = không)',
  vai_noi_dung_tho: 'Nội dung thô (gạch đầu dòng cũng được)',
  vai_noi_dung_tho_phu: 'Ví dụ: Nghỉ lễ 2/9, đi làm bù sáng thứ 7\nĐổi phần mềm chấm công, ra vào phải quét vân tay…',
  vai_trich_yeu: 'Trích yếu (công văn bắt đầu "V/v", thông báo/quyết định "Về việc")',
  vai_kinh_gui: 'Kính gửi (nhiều nơi cách nhau dấu phẩy)',
  vai_can_cu: 'Căn cứ (mỗi dòng một căn cứ)',
  vai_cac_dieu: 'Nội dung các Điều (mỗi dòng một Điều)',
  vai_noi_dung: 'Nội dung (mỗi đoạn cách nhau một dòng trống)',
  vai_tep_kem: 'Tệp đính kèm (tùy chọn — gửi kèm email khi ban hành)',
  vai_toi_da_10_tep: 'Tối đa 10 tệp (PDF/JPG/PNG/DOCX/XLSX).',
  vai_tao_ban_nhap: 'Tạo bản nháp',
  vai_loi_ngan_ai: 'Nội dung thô cần ít nhất 3 ký tự mới tạo được bản nháp.',
  vai_loi_ngan_tu_soan: 'Trích yếu và nội dung mỗi ô cần ít nhất 3 ký tự.',
  vai_chua_co_ket_qua_gate: 'Chưa có kết quả gate.',
  vai_moi_cong_dat: 'Mọi cổng kiểm tra đạt (✓).',
  vai_ma: 'Mã',
  vai_ket_qua: 'Kết quả',
  vai_ly_do: 'Lý do',
  vai_loi_ai: 'Lỗi AI',
  vai_loi_code: 'Lỗi code',
  vai_da_dinh_kem_tep: 'Đã đính kèm tệp.',
  vai_da_xoa_tep: 'Đã xóa tệp đính kèm.',
  vai_khong_mo_docx: 'Không mở được tệp DOCX.',
  vai_khong_tai_chi_tiet: 'Không tải được chi tiết.',
  vai_da_luu_sua: 'Đã lưu sửa đổi. Hệ thống đang dựng lại văn bản…',
  vai_tao_luc: 'Tạo {n}',
  vai_ai_soan_ngan: 'AI soạn',
  vai_tu_soan_ngan: 'Tự soạn',
  vai_so_lan_goi_ai: 'Số lần gọi lại AI: {n}',
  vai_so_x: 'Số: {n}',
  vai_qd_nghi_viec_x: 'Quyết định nghỉ việc — nghỉ {n}',
  vai_da_tu_khoa_x: 'Đã tự khóa tài khoản lúc {n}',
  vai_se_tu_khoa: 'Tài khoản sẽ tự khóa sau ngày nghỉ việc.',
  vai_an_xem_truoc: 'Ẩn xem trước',
  vai_xem_truoc: 'Xem trước văn bản',
  vai_dang_mo: 'Đang mở…',
  vai_dong_docx: 'Đóng DOCX online',
  vai_xem_docx: 'Xem DOCX online',
  vai_tep_kem_x: 'Tệp đính kèm ({n})',
  vai_chua_co_tep: 'Chưa có tệp đính kèm. Tệp đính kèm sẽ được gửi cùng email khi ban hành.',
  vai_dang_tai: 'Đang tải…',
  vai_dinh_kem_tep: 'Đính kèm tệp',
  vai_sua_van_xuoi: 'Sửa văn xuôi',
  vai_trich_yeu_ngan: 'Trích yếu',
  vai_kinh_gui_ngan: 'Kính gửi',
  vai_can_cu_ngan: 'Căn cứ',
  vai_cac_dieu_ngan: 'Các Điều',
  vai_luu_dung_lai: 'Lưu & dựng lại',
  vai_viet_lai_ai: 'Viết lại bằng AI',
  vai_da_yeu_cau_viet_lai: 'Đã yêu cầu AI viết lại.',
  vai_gui_lay_y_kien: 'Gửi lấy ý kiến',
  vai_da_mo_lay_y_kien: 'Đã mở lấy ý kiến trong 7 ngày. Email mời đã gửi tới những người trong phạm vi văn bản.',
  vai_tu_x: ' từ {n}',
  vai_han_gop_y: ' Hạn góp ý: {n} (còn {m} ngày).',
  vai_y_kien_ve_ho_thu: 'Ý kiến gửi về nằm trong trang Hòm thư ý kiến. Hết hạn, văn bản tự quay về Chờ duyệt để sửa đổi hoặc ban hành chính thức.',
  vai_ket_thuc_y_kien: 'Kết thúc lấy ý kiến',
  vai_da_ket_thuc_y_kien: 'Đã kết thúc lấy ý kiến. Văn bản quay về trạng thái chờ duyệt.',
  vai_trinh_ky: 'Trình ký',
  vai_da_trinh_ky: 'Đã trình ký.',
  vai_ban_hanh_cap_so: 'Ban hành (cấp số)',
  vai_da_ban_hanh_qd: 'Đã ban hành. Quyết định đã lưu vào hồ sơ nhân viên; đến ngày nghỉ việc tài khoản sẽ tự động bị khóa.',
  vai_da_ban_hanh: 'Đã ban hành. Nhân viên đã nhận thông báo.',
  vai_da_huy_nhap: 'Đã hủy bản nháp.',
  vai_voi_so_x: 'với số {n}',
  vai_gui_lai_email: 'Gửi lại email',
  vai_ai_khong_soan_duoc: 'AI không soạn được. Hãy bấm "Viết lại bằng AI" để thử lại; nếu vẫn lỗi, hãy tạo bản nháp mới ở chế độ "Tự soạn" và nhập văn xuôi trực tiếp.',
  vai_banner_du_thao: 'Dự thảo lấy ý kiến: soạn văn bản rồi bấm **Gửi lấy ý kiến** — người lao động góp ý trong **7 ngày** qua Hòm thư ý kiến (chọn mã văn bản). Hết hạn, văn bản tự quay về **Chờ duyệt** để sửa đổi hoặc ban hành chính thức; ý kiến xem ở trang Hòm thư ý kiến — lọc theo mã văn bản.',
  vai_dang_lay_y_kien_x: ' Đang lấy ý kiến: {n} văn bản.',
  vai_chua_co_van_ban_ai: 'Chưa có văn bản AI',
  vai_tao_ban_nhap_dau: 'Tạo bản nháp đầu tiên bằng nút phía trên.',
  vai_ve_viec: 'Về việc',
  vai_pham_vi: 'Phạm vi',
  vai_trang_thai: 'Trạng thái',
  vai_cap_nhat: 'Cập nhật',
  vai_chi_tiet: 'Chi tiết',
  vai_nghi_x: ' · nghỉ {n}',
  vai_han_x: ' · hạn {n}',

  // ================================ tro ly quan tri
  tlq_mo: 'Mở trợ lý quản trị',
  tlq_ten: 'Trợ lý quản trị',
  tlq_dong: 'Đóng',
  tlq_xin_loi: 'Xin lỗi, mình chưa trả lời được lúc này: {n}',
  tlq_cau_hoi: 'Câu hỏi',
  tlq_hoi_phong: 'Hỏi tổng quan, đi muộn, vắng, đơn chờ duyệt…',

  // ================================ che do sang/toi
  cd_sang: 'Chuyển sang giao diện sáng',
  cd_toi: 'Chuyển sang giao diện tối',
  cd_theo_may: 'Đang theo cài đặt máy — bấm để chọn thủ công',
  cd_ten_toi: 'Giao diện tối',
  cd_ten_sang: 'Giao diện sáng',
} as const;
