// Tu dien tieng VIET cho giao dien WEB. Chuoi nguoi dung doc PHẢI co du hai khoa vi + zh
// (xem tai_lieu/SONG-NGU-TRUNG.md) — khong hardcode chuoi trong component.
export const CHUOI_VI = {
  // ================================ chung / ngon ngu
  ngon_ngu: 'Ngôn ngữ',
  ngon_ngu_tieng_viet: 'Tiếng Việt',
  ngon_ngu_tieng_trung: 'Tiếng Trung',

  // ================================ khung: thanh ben + header
  thuong_hieu_phu: 'HR · Chấm công',
  chuyen_goc_nhin: 'Chuyển góc nhìn',
  mo_thanh_dieu_huong: 'Mở thanh điều hướng',
  dong_thanh_dieu_huong: 'Đóng thanh điều hướng',
  quan_tri: 'Quản trị',
  ca_nhan: 'Cá nhân',
  doi_mat_khau: 'Đổi mật khẩu',
  dang_xuat: 'Đăng xuất',

  // ================================ dang nhap
  dang_nhap: 'Đăng nhập',
  dang_nhap_mo_ta: 'Đăng nhập để quản lý chấm công và bảng công.',
  dang_nhap_bang_microsoft: 'Đăng nhập bằng Microsoft',
  hoac: 'hoặc',
  ten_dang_nhap: 'Tên đăng nhập',
  mat_khau: 'Mật khẩu',
  dang_dang_nhap: 'Đang đăng nhập…',
  dang_hoan_tat_dang_nhap: 'Đang hoàn tất đăng nhập…',
  dang_kiem_tra_phien: 'Đang kiểm tra phiên đăng nhập…',
  loi_khong_hoan_tat_sso: 'Không hoàn tất được đăng nhập Microsoft.',

  // ================================ doi mat khau
  doi_mk_hien_tai_do_admin: 'Mật khẩu hiện tại do quản trị đặt. Bạn phải đổi trước khi dùng hệ thống.',
  doi_mk_dang_xuat_moi_thiet_bi: 'Đổi mật khẩu sẽ đăng xuất mọi thiết bị khác.',
  mat_khau_hien_tai: 'Mật khẩu hiện tại',
  mat_khau_moi: 'Mật khẩu mới',
  nhap_lai_mat_khau_moi: 'Nhập lại mật khẩu mới',
  mat_khau_yeu_cau: 'Tối thiểu 8 ký tự, có cả chữ và số.',
  hai_lan_nhap_chua_khop: 'Hai lần nhập chưa khớp.',
  dang_doi: 'Đang đổi…',
  da_doi_mat_khau: 'Đã đổi mật khẩu. Vui lòng đăng nhập lại.',

  // ================================ cho duyet
  cho_phan_quyen: 'Chờ phân quyền',
  cho_duyet_mo_ta: 'Xin chào {ten}. Tài khoản của bạn đã xác thực thành công bằng Microsoft, nhưng chưa được quản trị viên phân quyền nên chưa vào được hệ thống.',
  cho_duyet_luu_y: 'Hãy báo bộ phận nhân sự để được cấp quyền. Sau khi được cấp, bạn chỉ cần đăng nhập lại là dùng được ngay.',
  cho_duyet_chua_co: 'Vẫn chưa được cấp quyền. Thử lại sau khi nhân sự báo đã xong.',
  cho_duyet_dang_kiem: 'Đang kiểm tra…',
  cho_duyet_kiem_lai: 'Tôi đã được cấp quyền — kiểm tra lại',

  // ================================ loi / trang trong
  khong_co_quyen: 'Không có quyền',
  khong_co_quyen_mo_ta: 'Tài khoản của bạn không được xem trang này.',
  khong_co_trang: 'Không có trang này',
  khong_co_trang_mo_ta: 'Đường dẫn {duong_dan} không tồn tại.',
  ve_tong_quan: 'Về tổng quan',

  // ================================ vai tro
  vai_tro_admin: 'Quản trị',
  vai_tro_nhan_su: 'Nhân sự',
  vai_tro_truong_phong: 'Trưởng phòng',
  vai_tro_truong_phong_nhan_su: 'TP nhân sự',
  vai_tro_nhan_vien: 'Nhân viên',
  vai_tro_cho_duyet: 'Chờ phân quyền',
  vai_tro_tbks: 'Trưởng ban kiểm soát',

  // ================================ nhom menu
  nhom_cham_cong: 'Chấm công',
  nhom_luong: 'Lương',
  nhom_nhan_su: 'Nhân sự',
  nhom_cong_viec_to_chuc: 'Công việc & tổ chức',
  nhom_truyen_thong_noi_bo: 'Truyền thông nội bộ',
  nhom_he_thong: 'Hệ thống',
  nhom_nhan_su_luong: 'Nhân sự & lương',
  nhom_tai_khoan_bao_mat: 'Tài khoản & bảo mật',
  nhom_tich_hop_du_lieu: 'Tích hợp & dữ liệu',

  // ================================ khu cai dat
  muc_cai_dat: 'Mục cài đặt',
  cai_dat_mo_ta: 'Các mục cấu hình của hệ thống. Chỉ hiện những mục vai trò của bạn được sửa.',

  // ================================ muc menu + phu
  menu_tong_quan: 'Tổng quan',
  menu_tong_quan_phu: 'Tình hình chấm công hôm nay',
  menu_khu_vuc_cua_toi: 'Khu vực của tôi',
  menu_khu_vuc_cua_toi_phu: 'Chấm công, đơn từ và hồ sơ của bạn',
  menu_cham_cong: 'Chấm công',
  menu_cham_cong_phu: 'Log đồng bộ từ máy ADMS',
  menu_bang_cong: 'Bảng công',
  menu_bang_cong_phu: 'Tổng hợp theo tháng',
  menu_ra_vao: 'Ra/vào',
  menu_ra_vao_phu: 'Cảnh báo ra/vào & xử lý',
  menu_bang_luong: 'Bảng lương',
  menu_bang_luong_phu: 'Tính lương, phiếu từng người',
  menu_phu_cap: 'Phụ cấp',
  menu_phu_cap_phu: 'Danh mục khoản · theo khối · cá nhân',
  menu_ung_luong: 'Ứng lương',
  menu_ung_luong_phu: 'Tạm ứng · duyệt · đã chi',
  menu_khieu_nai_luong: 'Khiếu nại lương',
  menu_khieu_nai_luong_phu: 'Khiếu nại phiếu lương của nhân viên',
  menu_nhan_vien: 'Nhân viên',
  menu_nhan_vien_phu: 'Hồ sơ, PIN máy, tài khoản',
  menu_de_nghi_nhan_su: 'Đề nghị thêm nhân sự',
  menu_de_nghi_nhan_su_phu: 'HR đề nghị, Admin duyệt một bước — hệ thống tự khởi tạo',
  menu_duyet_don: 'Duyệt đơn',
  menu_duyet_don_phu: 'Đơn từ & duyệt',
  menu_quan_ly_phep: 'Quản lý phép',
  menu_quan_ly_phep_phu: 'Tổng hợp ngày phép từng người',
  menu_so_ngoai_le: 'Sổ ngoại lệ',
  menu_so_ngoai_le_phu: 'Ngày bão, sự kiện đặc biệt — miễn đi muộn/về sớm/vắng',
  menu_hop_dong: 'Hợp đồng',
  menu_hop_dong_phu: 'Hạn hợp đồng, tìm trong nội dung',
  menu_ky_luat: 'Kỷ luật & vi phạm',
  menu_ky_luat_phu: 'Nội quy, nhắc nhở, giảm thưởng',
  menu_thoi_viec: 'Thôi việc',
  menu_thoi_viec_phu: 'Quy trình thôi việc: checklist, bàn giao, chốt',
  menu_cong_viec: 'Công việc',
  menu_cong_viec_phu: 'Giao việc, duyệt kết quả, lịch công việc',
  menu_to_chuc: 'Tổ chức & trách nhiệm',
  menu_to_chuc_phu: 'Cơ cấu, vị trí, JD, RACI, bao phủ',
  menu_kpi: 'KPI',
  menu_kpi_phu: 'Chấm điểm từ dữ liệu thật',
  menu_thong_bao: 'Thông báo',
  menu_thong_bao_phu: 'Đăng thông báo / gửi email / popup toàn công ty',
  menu_van_ban: 'Văn bản công ty',
  menu_van_ban_phu: 'Soạn bằng AI, ban hành, tài liệu công ty',
  menu_ho_thu_y_kien: 'Hòm thư ý kiến',
  menu_ho_thu_y_kien_phu: 'Tiếp nhận phản ánh, góp ý & ý kiến dự thảo',
  menu_cong_bo_phat_hanh: 'Công bố phát hành',
  menu_cong_bo_phat_hanh_phu: 'AI tổng hợp tính năng mới, gửi thông báo + popup',
  menu_cai_dat: 'Cài đặt',
  menu_cai_dat_phu: 'Chấm công, lương, tài khoản, tích hợp',
  menu_thiet_bi: 'Thiết bị',
  menu_thiet_bi_phu: 'Máy chấm công ZKTeco',
  menu_ca_lam: 'Ca làm việc',
  menu_ca_lam_phu: 'Giờ vào/ra, dung sai, ngưỡng OT',
  menu_dia_diem: 'Địa điểm',
  menu_dia_diem_phu: 'Đối chiếu GPS khi đi công tác',
  menu_ngay_le: 'Ngày lễ',
  menu_ngay_le_phu: 'Tết Nguyên đán phải tự thêm mỗi năm',
  menu_lam_bu: 'Ngày làm bù',
  menu_lam_bu_phu: 'Ngày được nghỉ, kiếm công bằng buổi làm bù',
  menu_tham_so_luong: 'Tham số lương',
  menu_tham_so_luong_phu: 'BHXH, thuế TNCN, giảm trừ gia cảnh',
  menu_tai_khoan: 'Tài khoản',
  menu_tai_khoan_phu: 'Người dùng và vai trò',
  menu_khoa_api: 'Khóa API',
  menu_khoa_api_phu: 'Cho hệ thống ngoài gọi vào',
  menu_nhat_ky: 'Nhật ký thao tác',
  menu_nhat_ky_phu: 'Ai sửa gì, khi nào',
  menu_dong_bo_erp: 'Đồng bộ ERP',
  menu_dong_bo_erp_phu: 'Kéo người dùng từ ERP cũ',
  menu_kho_tep: 'Kho tệp hồ sơ',
  menu_kho_tep_phu: 'Tệp đính kèm và đường dẫn đã lưu',
  menu_ma_dinh_danh: 'Mã định danh',
  menu_ma_dinh_danh_phu: 'Tra cứu theo mã, đối soát các nguồn',
} as const;
