// Tu dien tieng TRUNG (Gian the, thuong mai chuyen nghiep) cho giao dien WEB.
// Bat buoc dung dung tu trong bang thuat ngu (tai_lieu/SONG-NGU-TRUNG.md) — khong dich may.
// `satisfies` lam TypeScript bat luon khi quen mot khoa hoac them khoa lech so voi tieng Viet.
import type { CHUOI_VI } from './vi.ts';

export const CHUOI_ZH = {
  // ================================ chung / ngon ngu
  ngon_ngu: '语言',
  ngon_ngu_tieng_viet: '越南语',
  ngon_ngu_tieng_trung: '中文',

  // ================================ khung: thanh ben + header
  thuong_hieu_phu: 'HR · 考勤',
  chuyen_goc_nhin: '切换视角',
  mo_thanh_dieu_huong: '打开导航栏',
  dong_thanh_dieu_huong: '关闭导航栏',
  quan_tri: '管理',
  ca_nhan: '个人',
  doi_mat_khau: '修改密码',
  dang_xuat: '退出登录',

  // ================================ dang nhap
  dang_nhap: '登录',
  dang_nhap_mo_ta: '登录以管理考勤与工资表。',
  dang_nhap_bang_microsoft: '使用 Microsoft 登录',
  hoac: '或',
  ten_dang_nhap: '用户名',
  mat_khau: '密码',
  dang_dang_nhap: '正在登录…',
  dang_hoan_tat_dang_nhap: '正在完成登录…',
  dang_kiem_tra_phien: '正在检查登录状态…',
  loi_khong_hoan_tat_sso: '无法完成 Microsoft 登录。',

  // ================================ doi mat khau
  doi_mk_hien_tai_do_admin: '当前密码由管理员设置。使用系统前必须先修改。',
  doi_mk_dang_xuat_moi_thiet_bi: '修改密码将使其他所有设备退出登录。',
  mat_khau_hien_tai: '当前密码',
  mat_khau_moi: '新密码',
  nhap_lai_mat_khau_moi: '再次输入新密码',
  mat_khau_yeu_cau: '至少 8 个字符，包含字母和数字。',
  hai_lan_nhap_chua_khop: '两次输入不一致。',
  dang_doi: '正在修改…',
  da_doi_mat_khau: '密码已修改。请重新登录。',

  // ================================ cho duyet
  cho_phan_quyen: '待分配权限',
  cho_duyet_mo_ta: '您好，{ten}。您的账号已通过 Microsoft 验证成功，但尚未由管理员分配权限，暂时无法进入系统。',
  cho_duyet_luu_y: '请联系人事部门分配权限。权限分配后，重新登录即可使用。',
  cho_duyet_chua_co: '权限尚未分配。请在人事部门确认后重试。',
  cho_duyet_dang_kiem: '正在检查…',
  cho_duyet_kiem_lai: '已获权限——重新检查',

  // ================================ loi / trang trong
  khong_co_quyen: '无权限',
  khong_co_quyen_mo_ta: '您的账号无权查看此页面。',
  khong_co_trang: '页面不存在',
  khong_co_trang_mo_ta: '路径 {duong_dan} 不存在。',
  ve_tong_quan: '返回概览',

  // ================================ vai tro
  vai_tro_admin: '管理员',
  vai_tro_nhan_su: '人事',
  vai_tro_truong_phong: '部门主管',
  vai_tro_truong_phong_nhan_su: '人事主管',
  vai_tro_nhan_vien: '员工',
  vai_tro_cho_duyet: '待分配权限',
  vai_tro_tbks: '审计委员会主任',

  // ================================ nhom menu
  nhom_cham_cong: '考勤',
  nhom_luong: '工资',
  nhom_nhan_su: '人事',
  nhom_cong_viec_to_chuc: '工作与组织',
  nhom_truyen_thong_noi_bo: '内部沟通',
  nhom_he_thong: '系统',
  nhom_nhan_su_luong: '人事与工资',
  nhom_tai_khoan_bao_mat: '账号与安全',
  nhom_tich_hop_du_lieu: '集成与数据',

  // ================================ khu cai dat
  muc_cai_dat: '设置菜单',
  cai_dat_mo_ta: '系统配置项。仅显示您有权修改的菜单。',

  // ================================ muc menu + phu
  menu_tong_quan: '概览',
  menu_tong_quan_phu: '今日考勤概况',
  menu_khu_vuc_cua_toi: '我的区域',
  menu_khu_vuc_cua_toi_phu: '您的考勤、申请与档案',
  menu_cham_cong: '考勤',
  menu_cham_cong_phu: '考勤机同步的打卡记录',
  menu_bang_cong: '考勤表',
  menu_bang_cong_phu: '按月汇总',
  menu_ra_vao: '出入',
  menu_ra_vao_phu: '出入异常预警与处理',
  menu_bang_luong: '工资表',
  menu_bang_luong_phu: '计算工资、个人工资单',
  menu_phu_cap: '津贴',
  menu_phu_cap_phu: '津贴目录 · 按部门 · 个人',
  menu_ung_luong: '预支工资',
  menu_ung_luong_phu: '预支申请 · 审批 · 已发放',
  menu_khieu_nai_luong: '工资申诉',
  menu_khieu_nai_luong_phu: '员工工资单申诉',
  menu_nhan_vien: '员工',
  menu_nhan_vien_phu: '档案、考勤机 PIN、账号',
  menu_de_nghi_nhan_su: '新增员工申请',
  menu_de_nghi_nhan_su_phu: 'HR 提交申请，管理员一步审批——系统自动创建',
  menu_duyet_don: '审批申请',
  menu_duyet_don_phu: '申请与审批',
  menu_quan_ly_phep: '假期管理',
  menu_quan_ly_phep_phu: '汇总每位员工的假期天数',
  menu_so_ngoai_le: '考勤特批',
  menu_so_ngoai_le_phu: '台风日、特殊事件——免除迟到/早退/缺勤',
  menu_hop_dong: '合同',
  menu_hop_dong_phu: '合同期限、内容检索',
  menu_ky_luat: '纪律与违规',
  menu_ky_luat_phu: '规章制度、提醒、扣减奖金',
  menu_thoi_viec: '离职',
  menu_thoi_viec_phu: '离职流程：清单、交接、结清',
  menu_cong_viec: '工作',
  menu_cong_viec_phu: '分配任务、审批结果、工作日程',
  menu_to_chuc: '组织与职责',
  menu_to_chuc_phu: '组织架构、岗位、JD、RACI、覆盖',
  menu_kpi: 'KPI',
  menu_kpi_phu: '基于真实数据评分',
  menu_thong_bao: '通知',
  menu_thong_bao_phu: '发布通知 / 发送邮件 / 全公司弹窗',
  menu_van_ban: '公司制度',
  menu_van_ban_phu: 'AI 起草、发布、公司文档',
  menu_ho_thu_y_kien: '意见箱',
  menu_ho_thu_y_kien_phu: '接收反馈、建议与草案意见',
  menu_cong_bo_phat_hanh: '发布公告',
  menu_cong_bo_phat_hanh_phu: 'AI 汇总新功能，发送通知 + 弹窗',
  menu_cai_dat: '设置',
  menu_cai_dat_phu: '考勤、工资、账号、集成',
  menu_thiet_bi: '设备',
  menu_thiet_bi_phu: 'ZKTeco 考勤机',
  menu_ca_lam: '班次',
  menu_ca_lam_phu: '上下班时间、容差、加班阈值',
  menu_dia_diem: '地点',
  menu_dia_diem_phu: '出差时 GPS 比对',
  menu_ngay_le: '节假日',
  menu_ngay_le_phu: '春节假期需每年手动添加',
  menu_lam_bu: '补班日',
  menu_lam_bu_phu: '调休日，以补班换取工时',
  menu_tham_so_luong: '工资参数',
  menu_tham_so_luong_phu: '社保、个人所得税、专项附加扣除',
  menu_tai_khoan: '账号',
  menu_tai_khoan_phu: '用户与角色',
  menu_khoa_api: 'API 密钥',
  menu_khoa_api_phu: '供外部系统调用',
  menu_nhat_ky: '操作日志',
  menu_nhat_ky_phu: '谁在何时修改了什么',
  menu_dong_bo_erp: 'ERP 同步',
  menu_dong_bo_erp_phu: '从旧 ERP 导入用户',
  menu_kho_tep: '档案文件库',
  menu_kho_tep_phu: '已保存的附件与路径',
  menu_ma_dinh_danh: '识别码',
  menu_ma_dinh_danh_phu: '按编码查询、核对各数据源',

  // ================================ 我的区域：外壳 + 首页
  cn_loi_man_hinh: '此页面显示出现异常',
  cn_loi_man_hinh_mo_ta: '其他页面仍可正常使用——请切换到其他标签页后再回来，或刷新页面。若仍有问题，请将下方详细信息发给人事。',
  cn_ban: '您',
  cn_tab_trang_chu: '首页',
  cn_tab_don_tu: '申请单',
  cn_tab_luong: '工资',
  cn_tab_phep: '假期',
  cn_tab_khieu_nai: '申诉',
  cn_tab_ca_nhan: '个人',
  cn_ten_man_bang_cong: '我的考勤表',
  cn_ten_man_bang_cong_phu: '按月考勤数据',
  cn_ten_man_don_tu: '请假与申请单',
  cn_ten_man_don_tu_phu: '请假、补卡说明，跟踪审批状态',
  cn_ten_man_luong: '工资单',
  cn_ten_man_luong_phu: '本期工资计算依据',
  cn_ten_man_phep: '假期管理',
  cn_ten_man_phep_phu: '您的年假额度与休假记录',
  cn_ten_man_khieu_nai: '工资申诉',
  cn_ten_man_khieu_nai_phu: '发起并跟踪工资单申诉，与人事沟通',
  cn_ten_man_viec: '我的工作',
  cn_ten_man_viec_phu: '分配给我的工作、完成期限与待办步骤',
  cn_ten_man_y_kien: '意见箱',
  cn_ten_man_y_kien_phu: '提交建议、反馈、疑问并跟踪人事回复',
  cn_ten_man_ca_nhan: '个人',
  cn_ten_man_ca_nhan_phu: '档案、文件、合同、社保、设置',
  cn_xin_chao: '您好，{ten}',
  cn_thong_bao_phu_de: '来自领导层与人事的通知',
  cn_van_ban_phu_de: '规章制度、表单、政策',
  cn_ve_goc_nhin_quan_tri: '返回管理视角',
  cn_chua_gan_ca_lam_viec: '尚未分配班次',
  cn_ve_man_truoc: '返回上一页',
  cn_ve_trang_chu: '返回首页',
  cn_cac_man_khu_vuc: '我的区域各页面',
  cn_thu_tuc_thoi_viec_mo: '离职流程进行中',
  cn_con_muc_bat_buoc: '还有 {n} 项必办事项未完成——请完成以便管理员结清。',
  cn_moi_muc_xong: '所有事项已完成——等待管理员在门户 2 最终审批。',
  cn_mo_huong_dan: '打开指南',
  cn_cong_thang: '本月出勤',
  cn_ngay_da_co_du_lieu: '已有 {n} 天数据',
  cn_di_muon: '迟到',
  cn_lan_x: '{n} 次',
  cn_tong_x: '合计 {n}',
  cn_ot_ghi_nhan: '已记录加班',
  cn_chua_qua_duyet: '尚未审批',
  cn_phep_con: '剩余假期',
  cn_ngay_x: '{n} 天',
  cn_ngay_cho_duyet: '{n} 天待审批',
  cn_khong_co_don_cho_duyet: '没有待审批申请',
  cn_gio_vao: '上班时间',
  cn_gio_ra: '下班时间',
  cn_chua_co_du_lieu_cham_cong: '今天暂无考勤数据',
  cn_hom_nay_vang: '今天缺勤',
  cn_hom_nay_nghi_phep: '今天休假',
  cn_di_muon_x: '迟到 {n}',
  cn_dung_gio_vao_ca: '准点上班',
  cn_chua_quet_vao: '尚未打卡上班',
  cn_da_quet_ra: '已打卡下班',
  cn_chua_quet_ra: '尚未打卡下班',
  cn_con_x_den_gio: '还剩 {n}，至 {g}',
  cn_qua_gio_ra: '已过下班时间 · {n}',
  cn_dang_lam: '工作中 · {n}',
  cn_da_ket_thuc_ca: '今日班次已结束',
  cn_vao_ca: '上班',
  cn_het_ca: '下班',
  cn_quet_tai_may: '考勤机打卡',
  cn_lam_moi: '刷新',
  cn_xin_nghi_phep: '申请休假',
  cn_con_ngay_phep: '剩余 {n} 天年假',
  cn_giai_trinh_quen_quet: '补卡说明',
  cn_bu_gio_thieu: '补录缺失的上下班时间',
  cn_don_cua_toi: '我的申请',
  cn_don_dang_cho_duyet: '{n} 份申请待审批',
  cn_dang_ky_ot: '申请加班',
  cn_lam_them_gio_duyet_2_cap: '加班——两级审批',
  cn_don_khac: '其他申请',
  cn_don_khac_phu: '加班、换班、出差、迟到、早退、远程办公',
  cn_nghi_phep_phu: '年假、无薪假、病假…',
  cn_gio_lam_7_ngay: '最近 7 天工作时长',
  cn_vach_mo_8_gio: '浅线 = 行政班次标准 8 小时。',
  cn_cac_lan_quet: '今日打卡记录',
  cn_chua_co_lan_quet: '暂无打卡记录',
  cn_du_lieu_hien_ngay: '打卡后数据会立即显示。',
  cn_tuan_nay: '本周',
  cn_chuyen_can_thang: '本月出勤率',
  cn_so_ngay_du_cong: '截至今日，出满勤且无迟到的天数。',
  cn_chua_co_du_lieu_thang: '本月暂无数据。',
  cn_bang_cong_xuat_hien: '考勤机上传记录后，考勤表将会显示。',
  cn_can_chu_y_sap_toi: '需关注与即将到来',
  cn_ngay_thieu_gio_quet: '{n} 天缺少打卡记录',
  cn_bo_sung_giai_trinh: '请提交补卡说明补充',
  cn_giai_trinh: '补卡说明',
  cn_theo_doi_don_tu: '请在申请单页面跟踪状态',
  cn_xem_don: '查看申请',
  cn_don_cho_ban_duyet: '{n} 份申请待您审批',
  cn_ban_la_nguoi_duyet: '您是本部门的审批人',
  cn_di_duyet: '去审批',
  cn_khong_co_viec_can_chu_y: '没有需要关注的事项',
  cn_cong_va_don_on: '今日考勤与申请均正常',

  // ================================ 我的区域：每日状态标签
  cn_tt_nghi_phep: '休假',
  cn_tt_nghi_khong_luong: '无薪假',
  cn_tt_lam_bu: '补班',
  cn_tt_ngoai_le: '特批',
  cn_tt_cong_tac: '出差',
  cn_tt_lam_remote: '远程办公',
  cn_tt_vang: '缺勤',
  cn_tt_ngay_le: '法定假日',
  cn_tt_nghi_tuan: '周休',
  cn_tt_thieu_gio_quet: '缺少打卡（{n}）',
  cn_tt_di_muon: '迟到 {n}',
  cn_tt_du_cong: '出满勤',
  cn_tt_co_mat: '出勤',
  cn_thieu_gio_vao: '缺上班打卡',
  cn_thieu_gio_ra: '缺下班打卡',

  // ================================ 我的区域：考勤表页
  cn_thang_truoc: '上个月',
  cn_thang_sau: '下个月',
  cn_thang_x: '月 {n}',
  cn_tong_cong: '总出勤',
  cn_gio_lam: '工作时长',
  cn_tang_ca: '加班',
  cn_chi_tiet_tung_ngay: '每日明细',
  cn_muon_thieu_gio: '迟到/缺打卡',
  cn_cong: '天',
  cn_muon_phut: '迟到 {n} 分钟',
  cn_ve_som_phut: '早退 {n} 分钟',
  cn_thieu_gio_vao_mui_ten: '缺上班打卡 → {r}',
  cn_dang_ky_lam_them_ot: '申请加班（OT）→',
  cn_thay_sai_lech: '发现差异？提交补卡说明 →',
  cn_lich_thang: '月历',
  cn_ngay_chua_co_du_lieu: '当天暂无数据',
  cn_chua_den: '未到',

  // ================================ 我的区域：申请单
  cn_quy_phep_nam_x: '{n} 年年假额度',
  cn_con: '剩余',
  cn_da_dung_x_ngay: '已用 {n} 天',
  cn_chua_tru_x_ngay: '尚未扣除 {n} 天待审批',
  cn_tat_ca: '全部',
  cn_dang_cho: '待审批（{n}）',
  cn_da_duyet: '已批准',
  cn_tu_choi: '已拒绝',
  cn_khong_co_don_o_loc: '此筛选下没有申请单',
  cn_chon_tat_ca_xem: '选择“全部”可查看已提交的所有申请。',
  cn_da_gui: '已提交',
  cn_nguoi_duyet: '审批人',
  cn_hoan_tat: '已完成',
  cn_huy_don_nay: '撤销此申请？',
  cn_huy_don_mo_ta: '申请将被标记为已撤销，审批人无需再处理。',
  cn_huy_don: '撤销申请',
  cn_da_huy_don: '已撤销申请。',
  cn_ly_do_x: '事由：{n}',
  cn_duyet_cap_1: '已通过一级审批（部门主管）——等待审计委员会主任/管理员二级审批。审批完成后，请以照片提交加班成果。',
  cn_nop_ket_qua_ot: '提交加班成果',
  cn_don_giai_trinh_khong_huy: '补卡说明无法自行撤销——请联系人事处理。',
  cn_loai_nghi: '请假类型',
  cn_thoi_gian_nghi: '休假时间',
  cn_ca_ngay: '全天',
  cn_nua_ngay: '半天',
  cn_tu_ngay: '开始日期',
  cn_den_ngay: '结束日期',
  cn_nghi_nua_ngay_x: '休假半天 {n}',
  cn_ngay_nghi_khoang: '休假 {n} 天，{tu} → {den}',
  cn_con_lai_ngay_phep: '剩余 {n} 天年假',
  cn_ly_do: '事由',
  cn_viec_gia_dinh: '家事…',
  cn_huy: '取消',
  cn_gui_don: '提交申请',
  cn_da_gui_don: '申请已提交。审批人将立即收到通知。',
  cn_ngay_thieu_gio_he_thong: '缺少打卡的日期——系统已识别',
  cn_ngay: '日期',
  cn_gio_vao_de_xuat: '建议上班时间',
  cn_gio_ra_de_xuat: '建议下班时间',
  cn_ly_do_bat_buoc: '事由（必填）',
  cn_may_khong_nhan_khuon_mat: '考勤机无法识别人脸、外出开会…',
  cn_chi_dien_moc_thieu: '仅填写缺失的时间点。人事审批后，考勤表将自动重算。',
  cn_gui_giai_trinh: '提交说明',
  cn_da_gui_giai_trinh: '补卡说明已提交。人事审批后，考勤表将自动重算。',
  cn_lam_don: '新建申请',
  cn_loai_don: '申请类型',
  cn_luu_y_doi_ca: '换班需由人事在档案中调整新班次。此处申请仅为提议，不会自动更改您的班次。',
  cn_luu_y_thoi_viec: '离职申请须按合同提前告知：固定期限合同提前 30 天，无固定期限合同提前 45 天。',
  cn_luu_y_lam_them: '每月加班合计不超过 40 小时。申请超限时系统会提示。',
  cn_luu_y_ve_som: '申请获批后，当天即使早退超过 30 分钟也不会扣除半天出勤。',
  cn_luu_y_lam_remote: '远程办公获批的当天计满出勤，无需打卡。',
  cn_tu_gio: '开始时间',
  cn_den_gio: '结束时间',
  cn_gio_du_kien_ra_ve: '预计下班时间',
  cn_noi_den: '目的地',
  cn_noi_dung_cong_tac: '出差内容',
  cn_dang_ky_lam_them_tieu_de: '申请加班（OT）',
  cn_ngay_lam_them: '加班日期',
  cn_tai_lieu_kem: '附件（可选——1 个 PDF/JPG/PNG 文件）',
  cn_da_chon_tep: '已选择：{n}',
  cn_hop_ot_2_cap: '加班申请经两级审批：部门主管，再由审计委员会主任/管理员。审批通过后，您以照片提交加班成果，加班才会计入考勤。每月加班合计不超过 40 小时。',
  cn_ket_qua_ot: '加班成果 · {n}',
  cn_ket_qua_ot_huong_dan: '申请已审批通过——请提交 1 至 5 张工作成果照片，待审计委员会主任审批后计入考勤。',
  cn_kq_da_nop: '成果已提交——等待审计委员会主任审批。重新提交将覆盖旧版本。',
  cn_kq_da_duyet: '成果已审批通过——加班已计入考勤。',
  cn_kq_tu_choi: '成果被驳回{n}。您可以重新提交。',
  cn_anh_ket_qua: '成果照片（1–5 张 JPG/PNG）',
  cn_da_chon_x_anh: '已选择 {n} 张照片：{ten}',
  cn_ghi_chu_khong_bat_buoc: '备注（可选）',
  cn_dong: '关闭',
  cn_dang_gui: '正在提交…',
  cn_nop_ket_qua: '提交成果',
  cn_da_nop_kq_ot: '加班成果已提交。审计委员会主任/管理员审批后计入考勤表。',
  cn_loai_lam_them: '加班',
  cn_loai_doi_ca: '换班',
  cn_loai_cong_tac: '出差',
  cn_loai_thoi_viec: '离职',
  cn_loai_di_muon: '迟到',
  cn_loai_ve_som: '早退',
  cn_loai_lam_remote: '远程办公',
  cn_td_nghi_phep_nam: '年假休假',
  cn_td_nghi_khong_luong: '无薪休假',
  cn_td_nghi_om: '病假休假',
  cn_td_nghi_thai_san: '产假休假',
  cn_td_nghi_ket_hon: '婚假休假',
  cn_td_nghi_hieu: '丧假休假',
  cn_loai_phep_nam: '年假',
  cn_loai_khong_luong: '无薪假',
  cn_loai_om: '病假',
  cn_loai_thai_san: '产假',
  cn_loai_ket_hon: '婚假',
  cn_loai_hieu: '丧假',
  cn_ra_ve_x: '下班 {n}',
  cn_de_xuat_khoang: '建议 {v} – {r}',
  cn_nua_ngay_dot: ' · 半天',

  // ================================ 我的区域：工资页
  cn_ky_truoc: '上一期',
  cn_ky_sau: '下一期',
  cn_ky_thang_x: '工资期 {n}',
  cn_ky_chua_co_phieu: '本期暂无工资单。',
  cn_duoi_day_du_lieu_cham_cong: '以下是将作为计算依据的考勤数据——请提前核对，以便在结算前发现差异。',
  cn_cong_thuc_te: '实际出勤',
  cn_da_tru_gio_nghi_trua: '已扣除午休时间',
  cn_chua_duyet_tra_them: '尚未审批发放',
  cn_khong_phep: '无请假',
  cn_cong_thuc_te_chuan: '实际出勤 / 标准出勤',
  cn_chi_tiet_ky_thang: '工资期明细 {n}',
  cn_ngay_co_mat: '出勤天数',
  cn_ve_som: '早退',
  cn_chot_roi: '本期考勤已结清——以下数据为最终依据。',
  cn_chua_chot: '本期尚未结清。一次迟到打卡或一份获批申请仍可能使数据变化。',
  cn_chot_roi_phieu: '本期考勤已结清——工资单数据为最终依据。',
  cn_chua_chot_phieu: '本期尚未结清——工资单数据仍可能变化。',

  // ================================ 我的区域：个人页（档案）
  cn_thong_tin_chung: '基本信息',
  cn_tai_lieu: '文件',
  cn_hop_dong: '合同',
  cn_luong: '工资',
  cn_nguoi_phu_thuoc: '抚养人',
  cn_bhxh_bhyt: '社保 – 医保',
  cn_cong_viec: '工作',
  cn_thiet_bi: '设备',
  cn_cai_dat: '设置',
  cn_tk_chua_noi_ho_so: '账号尚未关联员工档案',
  cn_nho_nhan_su_gan: '请人事将此账号关联到您的档案后，个人信息才会在此显示。',
  cn_vao_lam_x: '{n} 入职',
  cn_tham_nien_x: '工龄 {n}',
  cn_nam_thang_x: '{n} 年 {m} 个月',
  cn_x_thang: '{n} 个月',
  cn_x_nam: '{n} 年',
  cn_chua_co_hop_dong_hieu_luc: '暂无生效合同',
  cn_ho_so_tai_lieu: '档案文件',
  cn_du_tai_lieu_bat_buoc: '必交文件已齐全',
  cn_con_thieu_tai_lieu: '还缺 {n} 份必交文件',
  cn_xem_chi_tiet: '查看详情',
  cn_pin_may: '考勤机 PIN',
  cn_so_tren_may: '考勤机上的号码',
  cn_ngay_vao: '入职日期',
  cn_chinh_thuc_x: '{n} 转正',
  cn_chua_co_ngay_chinh_thuc: '暂无转正日期',
  cn_hop_dong_hien_tai: '当前合同',
  cn_den_x: '至 {n}',
  cn_kxd_thoi_han: '无固定期限',
  cn_luong_hien_tai: '当前工资',
  cn_chua_co_qd_luong: '暂无工资决定书',
  cn_phu_cap_x_dong: '津贴 {n} 越南盾 · {m}',
  cn_thong_tin_ca_nhan: '个人信息',
  cn_sai_thong_tin: '信息有误？请向人事提交更正申请——您无法自行修改原始档案。',
  cn_ho_va_ten: '姓名',
  cn_ngay_sinh: '出生日期',
  cn_gioi_tinh: '性别',
  cn_nam: '男',
  cn_nu: '女',
  cn_dien_thoai: '电话',
  cn_email_cong_ty: '公司邮箱',
  cn_noi_o_hien_tai: '现居住地',
  cn_ma_so_thue: '税号',
  cn_tk_va_cham_cong: '账号与考勤',
  cn_ma_nhan_vien: '员工编号',
  cn_pin_tren_may: '考勤机 PIN',
  cn_chua_cap: '尚未发放',
  cn_cham_cong_dt: '手机打卡',
  cn_duoc_phep: '允许',
  cn_khong_quet_tai_may: '不允许——请在考勤机打卡',
  cn_mui_gio_tinh_cong: '考勤时区',
  cn_trang_thai: '状态',
  cn_dang_lam_viec: '在职',
  cn_da_nghi_viec: '已离职',
  cn_tien_do_ho_so: '必交档案进度',
  cn_chi_tinh_du_khi: '文件达到“已录入系统”才算齐全。仅离职时才产生的文件暂免。',
  cn_tt_da_len_phan_mem: '已录入系统',
  cn_tt_da_so_hoa: '已数字化',
  cn_tt_da_co_du_lieu: '已有数据',
  cn_tt_thieu: '缺失',
  cn_tai_lieu_do_nhan_su: '文件由人事上传和更新。缺哪份文件，请联系人事补充。',
  cn_hop_dong_hd_null: '系统中暂无生效合同。已签字的纸质合同仍然有效——请提醒人事上传，以便档案完整。',
  cn_loai_hop_dong: '合同类型',
  cn_thoi_han: '期限',
  cn_ngay_ky: '签订日期',
  cn_so_hop_dong: '合同编号',
  cn_chuc_danh: '职务',
  cn_noi_lam_viec: '工作地点',
  cn_hieu_luc: '有效期',
  cn_tu_x: '自 {n}',
  cn_luong_co_ban: '基本工资',
  cn_luong_phu_cap: '工资与津贴',
  cn_so_lieu_do_nhan_su: '数据由人事确认。各期工资单请在工资页面查看。',
  cn_muc_luong: '工资水平',
  cn_hinh_thuc_tra: '支付方式',
  cn_so_quyet_dinh: '决定书编号',
  cn_hieu_luc_tu: '生效日期',
  cn_qh_con: '子女',
  cn_qh_vo_chong: '配偶',
  cn_qh_cha: '父亲',
  cn_qh_me: '母亲',
  cn_qh_anh_chi_em: '兄弟姐妹',
  cn_qh_khac: '其他',
  cn_hd_thu_viec: '试用',
  cn_hd_xac_dinh: '固定期限',
  cn_hd_kxd: '无固定期限',
  cn_hd_thoi_vu: '季节性',
  cn_hd_ctv: '合作人员',
  cn_hd_hoc_viec: '实习',
  cn_ht_thang: '按月',
  cn_ht_ngay: '按日',
  cn_ht_gio: '按时',
  cn_ht_san_pham: '计件',
  cn_ht_khoan: '包干',
  cn_bh_moi: '新建',
  cn_bh_da_nop: '已提交',
  cn_bh_cq_duyet: '机构已批',
  cn_bh_tu_choi: '被驳回',
  cn_bh_hoan_thanh: '已完成',
  cn_lbh_bao_tang: '增员申报',
  cn_lbh_bao_giam: '减员申报',
  cn_lbh_dieu_chinh: '调整',
  cn_lbh_chot_so: '结册',
  cn_lbh_cap_the: '发放医保卡',
  cn_lbh_om_dau: '病假待遇',
  cn_lbh_thai_san: '生育待遇',
  cn_lbh_duong_suc: '康复休养',
  cn_lbh_tnld: '工伤',

  // ================================ 我的区域：假期页
  cn_quy_phep_nam: '年假额度',
  cn_chi_nghi_phep_tru: '仅已批准的年假才从额度中扣除。病假 / 无薪假不扣年假。',
  cn_tong_quy_phep: '年假总额',
  cn_da_dung: '已用',
  cn_con_lai: '剩余',
  cn_dang_cho_duyet: '待审批',
  cn_chi_tiet_cac_lan_nghi: '休假明细（{n} 年）',
  cn_chua_co_lan_nghi: '本年度暂无休假记录。',
  cn_nua_ngay_suffix: '（半天）',
  cn_nam_truoc: '上一年',
  cn_nam_sau: '下一年',
  cn_phep_nam_x: '{n} 年年假',
  cn_tt_cho_duyet: '待审批',
  cn_tt_da_duyet: '已批准',
  cn_tt_tu_choi: '已拒绝',
  cn_tt_da_huy: '已撤销',

  // ================================ 我的区域：抚养人 + 社保 + 工作 + 设备 + 设置
  cn_chua_khai_pt: '尚未登记抚养人',
  cn_pt_mo_ta: '抚养人用于个人所得税专项附加扣除。请向人事提交证明文件进行登记。',
  cn_giam_tru: '扣除额',
  cn_den_x_khoang: ' 至 {n}',
  cn_con_hieu_luc: ' · 仍有效',
  cn_chua_co_khoang: '暂无适用区间',
  cn_da_dang_ky: '已登记',
  cn_chua_dang_ky: '未登记',
  cn_so_so_bhxh: '社保手册号',
  cn_chua_co: '暂无',
  cn_ma_the_bhyt: '医保卡号',
  cn_co_quan_bhxh: '社保经办机构',
  cn_noi_kcb_bd: '首诊医疗机构',
  cn_cac_su_kien_gan_day: '近期事件',
  cn_muc_dong_x: '缴费基数 {n} 越南盾',
  cn_ho_so_x: ' · 档案 {n}',
  cn_vi_tri_hien_tai: '现任岗位',
  cn_phong_ban: '部门',
  cn_quan_ly_truc_tiep: '直属上级',
  cn_ca_lam_viec: '班次',
  cn_chua_gan_ca: '未分配班次',
  cn_lich_su_cong_viec: '工作履历',
  cn_tiep_nhan: '入职',
  cn_ket_thuc_thu_viec: '试用期结束',
  cn_chua_xac_nhan_tt: '尚未确认试用期结束',
  cn_chua_co_thiet_bi: '暂无发放的设备',
  cn_thiet_bi_mo_ta: '笔记本电脑、门禁卡…由人事在交接时登记到档案。',
  cn_loai: '类型',
  cn_hang: '品牌',
  cn_so_seri: '序列号',
  cn_ngay_nhan: '领用日期',
  cn_tinh_trang: '状态',
  cn_dang_dung: '使用中',
  cn_dx_khoi_ung_dung: '退出登录？',
  cn_dx_mo_ta: '您将需要使用用户名和密码重新登录。考勤数据不受影响。',
  cn_may_chu_noi_bo: '内部服务器 · {n}',
  cn_mui_gio_tinh_cong_utc: '考勤时区 UTC+{n}',
  cn_mk_nhap_lai_khong_khop: '两次输入的新密码不一致。',
  cn_da_doi_mk_chuyen: '密码已修改。正在返回登录页面…',

  // ================================ 个人通知
  tb_thuong: '普通',
  tb_quan_trong: '重要',
  tb_khan: '紧急',
  tb_can_giai_trinh: '需说明',
  tb_xem_ai_da_doc: '查看已读人员',
  tb_tai_van_ban: '下载公文（DOCX）',
  tb_tai_x: '下载：{n}',
  tb_da_gui_email: '✉ 已发送邮件',
  tb_dang_gui: '正在发送…',
  tb_gui_email: '发送邮件',
  tb_chua_gui_duoc: '未能发送：{n}',
  tb_da_giai_trinh: '已说明{ma}{luc}：{nd}',
  tb_giai_trinh_cua_ban: '您的说明（必填）',
  tb_nhap_giai_trinh: '请输入说明 / 承诺…',
  tb_gui_giai_trinh: '提交说明',
  tb_da_doc_x: '✓ 已读 {n}',
  tb_da_doc_hieu: '已读并知悉',
  tb_dang_luu: '正在保存…',
  tb_dang_thong_bao: '+ 发布通知',
  tb_dang_thong_bao_moi: '发布新通知',
  tb_tieu_de: '标题',
  tb_noi_dung: '内容',
  tb_tep_kem_tuy_chon: '附件（可选——PDF/JPG/PNG/DOCX/XLSX，随邮件发送）',
  tb_meo_trinh_bay: '邮件排版技巧：{a} → 标题带蓝色边框 · 行首 {b} → 项目符号 · {c} → 加粗。',
  tb_muc_do: '级别',
  tb_bat_buoc_giai_trinh: '要求必须说明',
  tb_hien_popup: '打开应用时弹窗（必须阅读）',
  tb_gui_email_toan_cty: '发送邮件给全公司',
  tb_dang_dang: '正在发布…',
  tb_dang: '发布',
  tb_xem_truoc_email: '预览邮件',
  tb_xem_truoc_email_cn: '邮件预览（再次点击“预览邮件”可更新）',
  tb_da_doc_tua: '已读人员 — {n}',
  tb_chua_ai_xac_nhan: '还没有人确认已读',
  tb_nhan_vien: '员工',
  tb_phong: '部门',
  tb_doc_luc: '阅读时间',
  tb_giai_trinh_cot: '说明',
  tb_loc_thong_bao: '筛选通知',
  tb_toan_cong_ty_x: '全公司（{n}）',
  tb_tat_ca_x: '全部（{n}）',
  tb_chua_co_thong_bao: '暂无通知',
  tb_khi_dang_thi_hien: '公司发布通知后，会显示在这里。',
  tb_da_gui_gt_ok: '说明已提交。',
  tb_da_xac_nhan_doc: '已确认已读。',
  tb_da_gui_email_ok: '邮件已发送。',
  tb_da_dang_thong_bao: '通知已发布。',

  // ================================ 我的工资单
  pl_chua_co_phieu: '暂无工资单',
  pl_phieu_hien_sau: '会计结算并审批当月工资期后，工资单才会显示。',
  pl_phieu_luong: '工资单',
  pl_nhan_vien_x: '员工：{n}',
  pl_ky_thang_xy: '{m}/{n} 月工资期',
  pl_chuyen_ky: '切换工资期',
  pl_ky_truoc: '上一期',
  pl_ky_sau: '下一期',
  pl_tai_pdf: '下载 PDF',
  pl_xuat_file: '导出文件',
  pl_thuc_nhan: '实发',
  pl_da_lam_tron_tu: '已由 {n} 越南盾四舍五入',
  pl_du_cong: '满勤',
  pl_mien_phat: '免罚',
  pl_tong_thu_nhap: '总收入',
  pl_khoan_x: '{n} 项',
  pl_tong_khau_tru: '总扣除',
  pl_ti_trong: '占比',
  pl_khau_tru_chiem: '扣除占收入总额的 {n}%',
  pl_thu_nhap: '收入',
  pl_luong_cb_theo_cong: '基本工资（按出勤）',
  pl_cong_xy: '{n}/{m} 天',
  pl_phu_cap_theo_cong: '津贴（按出勤）',
  pl_d_thang_xy: '{n} 越南盾/月 × {m}/{k}',
  pl_luong_theo_cong: '按出勤计薪',
  pl_lam_them_gio: '加班（OT）',
  pl_ngay_thuong: '工作日',
  pl_he_so_x: '系数 {n}',
  pl_chu_nhat: '周日',
  pl_ngay_le: '法定假日',
  pl_mien_thue: '（免税）',
  pl_thuong: '奖金',
  pl_phu_cap_khac: '其他津贴',
  pl_khau_tru: '扣除',
  pl_tien_luong_dong: '缴费工资：{n} 越南盾',
  pl_sau_giam_tru: '扣除后',
  pl_tru_khac: '其他扣除',
  pl_da_mien_phat_ky: '本期迟到/早退已免罚（不扣除）。',
  pl_cac_lan_dm_vs: '迟到早退明细',
  pl_can_cu_tinh_luong: '工资计算依据',
  pl_cong_chuan: '标准出勤',
  pl_luong_ngay_cong: '日工资',
  pl_muc_dong_bh: '社保缴费基数',
  pl_giam_tru_gia_canh: '家庭专项扣除',
  pl_thu_nhap_tinh_thue: '应纳税收入',
  pl_phep_nam: '年假',
  pl_con_ngay_xy: '剩余 {n} / {m} 天',
  pl_da_dung_x_ngay: '已用 {n} 天',
  pl_x_dang_cho_duyet: '{n} 天待审批',
  pl_co_so_cham_cong: '工资计算依据（考勤）',
  pl_gio_cong: '工作小时',
  pl_da_duyet_tu_tren: '上方已审批',
  pl_tong_x_ngay: '合计：{n} 天有数据',
  pl_chua_co_du_lieu_ky: '本期暂无考勤数据。',
  pl_chi_tiet_ky: '{m}/{n} 月明细',
  pl_quen_cham_cong: '忘记打卡',
  pl_sai_so_lieu: '数据有误？请提交申诉。请在 3 天内核对。',
  pl_khieu_nai: '申诉',
  pl_chi_hien_khi_duyet: '工资单仅在工资期已审批/发放后显示。如发现错误，请点击申诉本工资单发送给人事，或在“我的申请”中提交说明——每项都清楚列出以便核对。',
  pl_khieu_nai_phieu_x: '工资单申诉 {n}',
  pl_mo_ta_khoan: '请清楚说明您认为不正确的项目（出勤、奖金、津贴、扣除…），以便人事核对并回复。',
  pl_noi_dung_kn: '申诉内容',
  pl_anh_kem: '附件照片（可选多张——可选）',
  pl_da_chon_x_anh: '已选择 {n} 张照片：{ten}',
  pl_gui_khieu_nai: '提交申诉',
  pl_da_gui_kn: '申诉已提交。',
  pl_tra_loi_bo_sung: '回复 / 向人事补充信息…',
  pl_gui_tra_loi: '发送回复',
  pl_da_gui_tra_loi: '回复已发送。',
  pl_them_anh_minh_chung: '添加证明照片（可选多张）：',
  pl_da_them_x_anh: '已添加 {n} 张照片。',
  pl_khieu_nai_cua_ban: '您的工资单申诉',
  pl_ticket_da_dong: '工单已关闭（{n}）。',
  pl_lap_khieu_nai: '发起工资单申诉',
  pl_chua_co_phieu_kn: '暂无已审批的工资单可供申诉。',
  pl_chon_ky: '选择工资期',
  pl_lap_kn_ky_nay: '就本期发起申诉',
  pl_chua_co_kn: '暂无申诉',
  pl_kn_mo_ta: '您提交工资单申诉后，会在这里显示处理状态以及与人事的沟通记录。',
  pl_tt_moi: '新建',
  pl_tt_dang_xem: '处理中',
  pl_tt_chap_nhan: '已受理',
  pl_tt_tu_choi: '已拒绝',
  pl_thang_xy: '{m}/{n} 月',
  pl_da_tra: '已发放',
  pl_lan: '次',
  pl_ngay_unit: '天',
  pl_ky_x: '工资期 {n}',
  pl_csv_muc: '项目',
  pl_csv_loai: '类型',
  pl_csv_so_luong: '数量',
  pl_csv_don_gia: '单价',
  pl_csv_thanh_tien: '金额',
  pl_csv_ghi_chu: '备注',
  pl_csv_thuc_nhan: '实发',

  // ================================ 我的意见箱
  yk_y_kien_du_thao: '草案意见',
  yk_gop_y: '建议',
  yk_phan_anh: '反馈',
  yk_yeu_cau: '需求',
  yk_thac_mac: '疑问',
  yk_cho_xu_ly: '待处理',
  yk_da_tiep_nhan: '已受理',
  yk_da_hoan_tat: '已办结',
  yk_gui_y_kien_moi: '提交新意见',
  yk_ma_vb_du_thao: '草案编号（可选）',
  yk_khong_gan_vb: '不关联公文（一般建议）',
  yk_chon_ma_vb: '选择要提出意见的草案编号',
  yk_du_thao: '草案',
  yk_han_x: '（截止 {n}）',
  yk_loai_y_kien: '意见类型',
  yk_chon_loai: '选择类型',
  yk_vi_du_tieu_de: '例如：建议为缝纫线增加风扇',
  yk_trinh_bay_ro: '请清楚说明您的意见、顾虑或需求…',
  yk_gui_y_kien: '提交意见',
  yk_chua_gui_y_kien: '您尚未提交任何意见',
  yk_moi_gop_y: '所有建议、反馈、需求都会由人事受理并回复。',
  yk_mo_lai_du_thao: '重新打开草案',
  yk_thu_gon: '收起',
  yk_xem_trao_doi: '查看沟通（{n}）',
  yk_trao_doi_them: '与人事进一步沟通…',
  yk_da_gui_ok: '已提交。人事将在此处及您的邮箱受理并回复。',
  yk_da_gui_dt: '草案意见已提交。人事将受理并回复。',

  // ================================ 我的工作
  vt_khong_con_viec: '没有待办工作了。',
  vt_con_viec_x: '您还有 {n} 项工作未完成。',
  vt_danh_sach: '列表',
  vt_lich_gantt: '日程（甘特图）',
  vt_chua_co_cong_viec: '暂无工作',
  vt_khi_giao_viec: '被分配工作后，会显示在这里，附截止日期与待办步骤。',
  vt_qua_han: '已逾期（{n}）',
  vt_den_han: '即将到期（{n}）',
  vt_dang_lam: '进行中（{n}）',
  vt_moi_giao: '新分配（{n}）',
  vt_cho_duyet: '待审批（{n}）',
  vt_da_xong: '已完成（{n}）',
  vt_khong_co: '无',
  vt_han_x: '截止 {n} {g}',
  vt_buoc_xy: '{x}/{y} 步',

  // ================================ 个人概览
  dcn_tong_quan_rieng: '这是 {n} 月您个人的概览。',
  dcn_ban_co_tb: '您有 {n} 条通知需要说明。',
  dcn_mo_ngay: '立即打开 →',
  dcn_cong_thang_nay: '本月出勤',
  dcn_co_mat_x_ngay: '出勤 {n} 天',
  dcn_phep_con_lai: '剩余假期',
  dcn_da_dung_xy: '已用 {x}/{y}',
  dcn_thong_bao_moi: '新通知',
  dcn_chua_doc_bam: '未读——点击查看',
  dcn_da_doc_het: '已全部读完',
  dcn_don_cho_duyet: '待审批申请',
  dcn_nghi_phep_giai_trinh: '请假、补卡说明',
  dcn_nghi_le_sap_toi: '即将到来的节假日',
  dcn_chua_co_ngay_le: '近期日历中暂无节假日。',
  dcn_loi_tat: '快捷入口',
  dcn_xin_nghi_giai_trinh: '请假 / 补卡说明',
  dcn_thong_bao_cty: '公司通知',
  dcn_tai_lieu_cty: '公司文件',
  dcn_ho_so_cua_toi: '我的档案',
  dcn_khong_tai_duoc: '无法加载概览。',

  // ================================ 个人助手
  tl_mo_tro_ly: '打开助手',
  tl_tro_ly_nhan_su: '人事助手',
  tl_xoa_lich_su: '清除记录',
  tl_xoa_toan_bo: '删除您的全部对话记录',
  tl_xoa: '删除',
  tl_dang_tra_loi: '正在回复',
  tl_cho_xac_nhan: '等待确认',
  tl_xin_loi: '抱歉，我暂时无法回答。',
  tl_yeu_cau_khong_hop_le: '此请求无效，我无法发送。',
  tl_luu_y: '请注意：',
  tl_da_gui_thanh_cong: '已成功提交：{n}。您可以在“我的申请”标签中查看状态。{them}',
  tl_khong_ket_noi: '无法连接服务器。',
  tl_may_chu_ban: '服务器正忙或刚重启——请几分钟后再试。',
  tl_chua_gui_duoc: '未能提交：{n}',
  tl_da_bo_qua: '已忽略——不会发送任何内容。',
  tl_cau_hoi: '提问',
  tl_hoi_phong: '询问假期、出勤、加班、换班、规章制度…',
  tl_gui: '发送',

  // ================================ 离职助手
  tv_tro_ly_thoi_viec: '离职流程助手',
  tv_thu_tuc_thoi_viec: '离职流程',
  tv_con_x_muc: '还有 {n} 项必办事项未完成。',
  tv_muc_ke_tiep: '下一项：{n}。',
  tv_ngay_lv_cuoi: '最后工作日：{n}',
  tv_xac_nhan_x: '确认：{n}',
  tv_mo_huong_dan_tv: '打开流程指南',

  // ================================ 通知弹窗
  pp_khan: '紧急',
  pp_giai_trinh_bat_buoc: '说明（必填）',
  pp_nhap_giai_trinh: '请输入您的说明…',
  pp_yeu_cau_nhap: '此通知要求您填写说明（至少 5 个字符）。',
  pp_gui_gt_xac_nhan: '提交说明并确认',
  pp_con_x_tb: '还有 {n} 条通知',

  // ================================ 通知铃铛
  cb_chua_doc_x: '（{n} 条未读）',
  cb_danh_dau_da_doc: '标记为已读',
  cb_tat_ca: '全部',
  cb_chua_xem: '未读',
  cb_cho_duyet: '待审批',
  cb_khong_con_chua_xem: '没有未读通知了。',
  cb_khong_co_cho_duyet: '没有待审批的通知。',
  cb_chua_co_thong_bao: '暂无通知。',
  cb_da_xem: '已读',

  // ================================ 公司文件（个人部分）
  vb_van_ban_ban_hanh: '正式发文',
  vb_van_ban_cong_ty_phu: '通知、带文号的正式发文与公司文件——统一入口。',
  vb_cac_muc_vb: '公司文件分类',
  vb_chua_co_van_ban: '暂无文件',
  vb_nhan_su_se_dang: '人事将在此发布通知、规章制度与表单。',
  vb_tai: '下载',
  vb_chua_co_vb_ban_hanh: '暂无正式发文',
  vb_van_ban_cho_ban: '发给您的带文号的公文将显示在这里。',
  vb_so_ky_hieu: '文号',
  vb_loai: '类型',
  vb_trich_yeu: '摘要',
  vb_phat_hanh: '发布',
  vb_tai_docx: '下载 DOCX',
  vb_dm_quyet_dinh: '决定',
  vb_dm_cong_van: '公文',
  vb_dm_noi_quy: '规章制度',
  vb_dm_bieu_mau: '表单',
  vb_dm_chinh_sach: '政策',
  vb_dm_huong_dan: '指南',
  vb_dm_khac: '其他',

  // ================================ 公共标签（thanh_phan.tsx）
  thp_cho_duyet_2: '待审计委员会主任/管理员',
  thp_tu_dong: '自动',
  thp_nguon_may: '考勤机',
  thp_nguon_dien_thoai: '手机',
  thp_nguon_thu_cong: '手工录入',
} as const satisfies Record<keyof typeof CHUOI_VI, string>;
