// Tu dien tieng TRUNG (Gian the, thuong mai chuyen nghiep) cho giao dien WEB.
// Bat buoc dung dung tu trong bang thuat ngu (tai_lieu/SONG-NGU-TRUNG.md) — khong dich may.
// `satisfies` lam TypeScript bat luon khi quen mot khoa hoac them khoa lech so voi tieng Viet.
import type { CHUOI_VI } from './vi.ts';

export const CHUOI_ZH = {
  // ================================ chung / ngon ngu
  ngon_ngu: '语言',
  ngon_ngu_tieng_viet: '越南语',
  ngon_ngu_tieng_trung: '中文',

  // ================================ khung: thanh ben + header
  thuong_hieu_phu: 'HR · 考勤',
  chuyen_goc_nhin: '切换视角',
  mo_thanh_dieu_huong: '打开导航栏',
  dong_thanh_dieu_huong: '关闭导航栏',
  quan_tri: '管理',
  ca_nhan: '个人',
  doi_mat_khau: '修改密码',
  dang_xuat: '退出登录',

  // ================================ dang nhap
  dang_nhap: '登录',
  dang_nhap_mo_ta: '登录以管理考勤与工资表。',
  dang_nhap_bang_microsoft: '使用 Microsoft 登录',
  hoac: '或',
  ten_dang_nhap: '用户名',
  mat_khau: '密码',
  dang_dang_nhap: '正在登录…',
  dang_hoan_tat_dang_nhap: '正在完成登录…',
  dang_kiem_tra_phien: '正在检查登录状态…',
  loi_khong_hoan_tat_sso: '无法完成 Microsoft 登录。',

  // ================================ doi mat khau
  doi_mk_hien_tai_do_admin: '当前密码由管理员设置。使用系统前必须先修改。',
  doi_mk_dang_xuat_moi_thiet_bi: '修改密码将使其他所有设备退出登录。',
  mat_khau_hien_tai: '当前密码',
  mat_khau_moi: '新密码',
  nhap_lai_mat_khau_moi: '再次输入新密码',
  mat_khau_yeu_cau: '至少 8 个字符，包含字母和数字。',
  hai_lan_nhap_chua_khop: '两次输入不一致。',
  dang_doi: '正在修改…',
  da_doi_mat_khau: '密码已修改。请重新登录。',

  // ================================ cho duyet
  cho_phan_quyen: '待分配权限',
  cho_duyet_mo_ta: '您好，{ten}。您的账号已通过 Microsoft 验证成功，但尚未由管理员分配权限，暂时无法进入系统。',
  cho_duyet_luu_y: '请联系人事部门分配权限。权限分配后，重新登录即可使用。',
  cho_duyet_chua_co: '权限尚未分配。请在人事部门确认后重试。',
  cho_duyet_dang_kiem: '正在检查…',
  cho_duyet_kiem_lai: '已获权限——重新检查',

  // ================================ loi / trang trong
  khong_co_quyen: '无权限',
  khong_co_quyen_mo_ta: '您的账号无权查看此页面。',
  khong_co_trang: '页面不存在',
  khong_co_trang_mo_ta: '路径 {duong_dan} 不存在。',
  ve_tong_quan: '返回概览',

  // ================================ vai tro
  vai_tro_admin: '管理员',
  vai_tro_nhan_su: '人事',
  vai_tro_truong_phong: '部门主管',
  vai_tro_truong_phong_nhan_su: '人事主管',
  vai_tro_nhan_vien: '员工',
  vai_tro_cho_duyet: '待分配权限',
  vai_tro_tbks: '审计委员会主任',

  // ================================ nhom menu
  nhom_cham_cong: '考勤',
  nhom_luong: '工资',
  nhom_nhan_su: '人事',
  nhom_cong_viec_to_chuc: '工作与组织',
  nhom_truyen_thong_noi_bo: '内部沟通',
  nhom_he_thong: '系统',
  nhom_nhan_su_luong: '人事与工资',
  nhom_tai_khoan_bao_mat: '账号与安全',
  nhom_tich_hop_du_lieu: '集成与数据',

  // ================================ khu cai dat
  muc_cai_dat: '设置菜单',
  cai_dat_mo_ta: '系统配置项。仅显示您有权修改的菜单。',

  // ================================ muc menu + phu
  menu_tong_quan: '概览',
  menu_tong_quan_phu: '今日考勤概况',
  menu_khu_vuc_cua_toi: '我的区域',
  menu_khu_vuc_cua_toi_phu: '您的考勤、申请与档案',
  menu_cham_cong: '考勤',
  menu_cham_cong_phu: '考勤机同步的打卡记录',
  menu_bang_cong: '考勤表',
  menu_bang_cong_phu: '按月汇总',
  menu_ra_vao: '出入',
  menu_ra_vao_phu: '出入异常预警与处理',
  menu_bang_luong: '工资表',
  menu_bang_luong_phu: '计算工资、个人工资单',
  menu_phu_cap: '津贴',
  menu_phu_cap_phu: '津贴目录 · 按部门 · 个人',
  menu_ung_luong: '预支工资',
  menu_ung_luong_phu: '预支申请 · 审批 · 已发放',
  menu_khieu_nai_luong: '工资申诉',
  menu_khieu_nai_luong_phu: '员工工资单申诉',
  menu_nhan_vien: '员工',
  menu_nhan_vien_phu: '档案、考勤机 PIN、账号',
  menu_de_nghi_nhan_su: '新增员工申请',
  menu_de_nghi_nhan_su_phu: 'HR 提交申请，管理员一步审批——系统自动创建',
  menu_duyet_don: '审批申请',
  menu_duyet_don_phu: '申请与审批',
  menu_quan_ly_phep: '假期管理',
  menu_quan_ly_phep_phu: '汇总每位员工的假期天数',
  menu_so_ngoai_le: '考勤特批',
  menu_so_ngoai_le_phu: '台风日、特殊事件——免除迟到/早退/缺勤',
  menu_hop_dong: '合同',
  menu_hop_dong_phu: '合同期限、内容检索',
  menu_ky_luat: '纪律与违规',
  menu_ky_luat_phu: '规章制度、提醒、扣减奖金',
  menu_thoi_viec: '离职',
  menu_thoi_viec_phu: '离职流程：清单、交接、结清',
  menu_cong_viec: '工作',
  menu_cong_viec_phu: '分配任务、审批结果、工作日程',
  menu_to_chuc: '组织与职责',
  menu_to_chuc_phu: '组织架构、岗位、JD、RACI、覆盖',
  menu_kpi: 'KPI',
  menu_kpi_phu: '基于真实数据评分',
  menu_thong_bao: '通知',
  menu_thong_bao_phu: '发布通知 / 发送邮件 / 全公司弹窗',
  menu_van_ban: '公司制度',
  menu_van_ban_phu: 'AI 起草、发布、公司文档',
  menu_ho_thu_y_kien: '意见箱',
  menu_ho_thu_y_kien_phu: '接收反馈、建议与草案意见',
  menu_cong_bo_phat_hanh: '发布公告',
  menu_cong_bo_phat_hanh_phu: 'AI 汇总新功能，发送通知 + 弹窗',
  menu_cai_dat: '设置',
  menu_cai_dat_phu: '考勤、工资、账号、集成',
  menu_thiet_bi: '设备',
  menu_thiet_bi_phu: 'ZKTeco 考勤机',
  menu_ca_lam: '班次',
  menu_ca_lam_phu: '上下班时间、容差、加班阈值',
  menu_dia_diem: '地点',
  menu_dia_diem_phu: '出差时 GPS 比对',
  menu_ngay_le: '节假日',
  menu_ngay_le_phu: '春节假期需每年手动添加',
  menu_lam_bu: '补班日',
  menu_lam_bu_phu: '调休日，以补班换取工时',
  menu_tham_so_luong: '工资参数',
  menu_tham_so_luong_phu: '社保、个人所得税、专项附加扣除',
  menu_tai_khoan: '账号',
  menu_tai_khoan_phu: '用户与角色',
  menu_khoa_api: 'API 密钥',
  menu_khoa_api_phu: '供外部系统调用',
  menu_nhat_ky: '操作日志',
  menu_nhat_ky_phu: '谁在何时修改了什么',
  menu_dong_bo_erp: 'ERP 同步',
  menu_dong_bo_erp_phu: '从旧 ERP 导入用户',
  menu_kho_tep: '档案文件库',
  menu_kho_tep_phu: '已保存的附件与路径',
  menu_ma_dinh_danh: '识别码',
  menu_ma_dinh_danh_phu: '按编码查询、核对各数据源',
} as const satisfies Record<keyof typeof CHUOI_VI, string>;
